### ISSUE TITLE
"parsing remote object value: unexpected end of JSON input" followed by "panic: GoError: parsing remote object value: unexpected end of JSON input"

### ISSUE THREAD

**Issue by spapaseit** [grafana/xk6-browser#1060]
### Brief summary

I have written k6 test for a client's single page app. 
After logging into the SPA, the application does an internal request to fetch "user cache" data. The response of that request is an 18-thousand (!!!) line long JSON object. At that point k6 show a warning in the console that says: 

```WARN[0019] object is too large and will be parsed partially  source=browser-console-api``` (which, you know, fair enough)

followed by the error:

```panic: GoError: parsing remote object value: unexpected end of JSON input```

There is nothing I can (or should!) do about the SPA's request to load that user cache object, but is there a way for me to either let k6 ignore that object, or work around this issue in any way?

### xk6-browser version

0.8.1 (k6 v0.46.0)

### OS

Windows 10

### Chrome version

117.0.5938.134

### Steps to reproduce the problem

Unfortunately, there isn't a script I can provide to reproduce, as it's very specific to this client's web application.

### Expected behaviour

k6 parses the object successfully. Alternatively, k6 provides a way to ignore/bypass the parsing of certain responses.

### Actual behaviour

k6 crashes

**Comment by inancgumus** [comment]
Duplicate: https://github.com/grafana/xk6-browser/issues/987.
