### ISSUE TITLE
Old version shipping with xk6

### ISSUE THREAD

**Issue by peterkarman1** [grafana/xk6-browser#1071]
### Brief summary

When using xk6 to compile with extensions, the version of xk6 browser is an older one that still requires importing chromium.

This version has bugs beyond the syntax changes so would love to see it be updated properly

### xk6-browser version

any

### OS

any

### Chrome version

any

### Steps to reproduce the problem

Build xk6 binary
  xk6 build 
  
  
  Use the sample from the documentation and receive the error

### Expected behaviour

You can follow the documentation

### Actual behaviour

You cannot follow the documentation

**Comment by ka3de** [comment]
Hi @peterkarman1. Could you please add this question in our [community forum](https://community.grafana.com/c/grafana-k6/k6-browser/). Also, please, try to add more details to the issue, such as the specific documentation section that you are following, the executed command and resulting error. Thank you.
