### ISSUE TITLE
Switch browser tab with bringToFront() doesnt work in my test

### ISSUE THREAD

**Issue by rajjnish29** [grafana/xk6-browser#1088]
### Brief summary

I have a browser test, where after clicking a button on home page a new browser tab opens up. I need to switch to new browser tab and perform further actions on some web elements in the test script.

I have tried to use bringToFront() to switch to new tab but it doesnt seem to be working for me. is it the right method to use to switch browser tab? 

any suggestion how to handle this case with K6?

Thanks,
Raj

### xk6-browser version

k6 v0.46.0 (2023-08-14T13:23:26+0000/v0.46.0-0-gcbd9e9ad, go1.20.7, linux/amd64)

### OS

Ubuntu

### Chrome version

Version 118.0.5993.88 (Official Build) (64-bit)

### Steps to reproduce the problem

I cant provide the URL at the moment to reproduce the exact issue because its not a public web app.

However, the step that mentioned in summary is pretty much what happens.

  // click on button to open the new browser tab:
```
  const openNewPage = page.locator(newPage);
  page.waitForSelector(newPage, { timeout: 60000, visible: true });
  openNewPage.click();
  console.log('Clicked on the button to open new browser tab');
  await sleep(5);
```

After performing following step:

```
  await page.bringToFront();
  console.log('Focused on the new Tab...');
```

when i check  `console.log('Current URL after opening editor: ', page.url());` in the next step, the URL is still of the previous page and not of the new tab page.

I am not sure if i am something wrong or need to change something here to make it work. would appreciate any help or suggestions.

### Expected behaviour

Switch to the new browser tab with page.bringToFront() 

### Actual behaviour

cant switch to new tab

**Comment by inancgumus** [comment]
Could you please ask questions on [our community forum](https://community.grafana.com/c/grafana-k6/k6-browser/79)? Please also make sure to include a test HTML and script for us to reproduce the issue. Thank you.
