### ISSUE TITLE
unknown module: k6/x/browser

### ISSUE THREAD

**Issue by QAInsights** [grafana/xk6-browser#112]
I installed k6 and xk6 and tried the sample code. But I am getting the below error in Window 10.

![image](https://user-images.githubusercontent.com/2826376/141693318-e26b6a30-688d-4d3e-a985-bf4c5277f6ef.png)

```
import launcher from "k6/x/browser";

export default function() {
    const browser = launcher.launch('chromium', { headless: false });
    const context = browser.newContext();
    const page = context.newPage();
    page.goto('http://whatsmyuseragent.org/', { waitUntil: 'load' });
    const dimensions = page.evaluate(() => {
        return {
            width: document.documentElement.clientWidth,
            height: document.documentElement.clientHeight,
            deviceScaleFactor: window.devicePixelRatio
        };
    });
    console.log(JSON.stringify(dimensions));
    page.close();
    browser.close();
}
```

**Comment by LaserPhaser** [comment]
you have to use newly built xk6 binary to be able to run it.

**Comment by imiric** [comment]
Like @LaserPhaser says, you need to run the examples with the binary built by xk6. See the installation instructions in the README or download the pre-compiled binary from the [Releases page](https://github.com/grafana/xk6-browser/releases).

I'll clarify the usage instructions in the README since that might not be clear enough.

**Comment by QAInsights** [comment]
@imiric @LaserPhaser I built the binary, but when I try to run the script, it is prompting to open the application. I do have Chrome installed in my system.

![image](https://user-images.githubusercontent.com/2826376/141834139-48f796af-fe61-4661-ae2a-c382dbe2ab1c.png)

**Comment by imiric** [comment]
@QAInsights Please use the [community forum](https://community.k6.io/c/xk6-browser/14) for support questions. GitHub issues are for tracking bugs or suggesting features.

There are other Windows users on the forum who can help you with your issue.

**Comment by QAInsights** [comment]
@imiric this is not a support question, it's an issue :) please check.
