### ISSUE TITLE
[Test] Add Basic Authentication Tests

### ISSUE THREAD

**Issue by unlikelyzero** [grafana/xk6-browser#1127]
### Feature Description

I recently migrated from v0.44 to v0.48 and am using basic authentication. I would like to provide a way to ensure that basic authentication continues to work between versions (especially if #1117 goes through).

How would you recommend I get started in contributing basic auth tests? I didn't see anything in the k6 http test suite.

```js
  
  // Create a new context with the basic auth credentials
  const contextWithAuth = await browser.newContext({
    httpCredentials: {
      username: k6,
      password: k6,
    },
  });

  const page = contextWithAuth.newPage();
  ```

**Comment by inancgumus** [comment]
Duplicate.
