### ISSUE TITLE
Determine best way of handling file outputs with multiple VUs

### ISSUE THREAD

**Issue by imiric** [grafana/xk6-browser#115]
Currently the extension has been mostly tested with a single VU. Running with multiple VUs (e.g. `xk6-browser run --vus 5 --iterations 5 <script>`) will spawn multiple browser sessions/windows, but the behavior is not well defined at the moment, specifically about what should happen with APIs that write to the filesystem.

Right now this is only the case for `Page.screenshot()`, but in the future we'll add support for [capturing video](https://github.com/grafana/xk6-browser/issues/103), [download handling](https://github.com/grafana/xk6-browser/issues/98) (which would be done by the browser, so it's not a direct concern), as well as allowing output of the data generated by [`Page.pdf()`](https://github.com/grafana/xk6-browser/issues/106).

A possible approach would be to handle it as browsers do and append a numbered suffix, e.g. `file (1).png`, `file (2).png`, etc. Something more flexible could be to use a filename template like `file_<VU>-<iteration>-<timestamp>.png`, and allowing it to be customized in the script.

This is a prerequisite issue for #98, #103, #106 and any other API that writes to the filesystem.

**Comment by imiric** [comment]
I'm taking a look at this issue and an additional note:

It's already possible to template filenames with `page.screenshot()`, e.g.: ```page.screenshot({ path: `screenshot-${__VU}-${__ITER}-${Date.now()}.png` })```. This would ensure that filenames are unique per VU, iteration or whatever other criteria is needed by the user. I think this is flexible enough and doesn't require any changes, we just need to document it properly. The same approach could be used for other APIs that write to disk as well.

@inancgumus @robingustafsson Do you think we should do something more sophisticated here?

**Comment by inancgumus** [comment]
It looks like a practical solution, but there is a possibility that leaving naming their files uniquely to users can be error-prone.

**Comment by imiric** [comment]
@inancgumus Sure, but they're developers, they should be aware of templating. :) As a developer, I'd prefer to have direct control over this rather than the tool being needlessly smart and deciding for me.

Do you have an alternative suggestion?

My vote is to go with this approach, and if so, we could close this issue, as there's nothing to change. @robingustafsson WDYT?

**Comment by inancgumus** [comment]
Maybe we can generate a unique filename **only** when a user doesn't give us a path, like:

```js
page.screenshot()
// automatically generate a unique filename

page.screenshot({ path: `screenshot-${__VU}-${__ITER}-${Date.now()}.png` })
// leave it to the user and document that the files may be overwritten
```

**Comment by imiric** [comment]
Yeah, the current implementation makes sense to me as well, I wouldn't want to change it. And we could presumably do the same thing for the new APIs.

OK, let's wait for @robingustafsson before closing this then.

**Comment by imiric** [comment]
@robingustafsson Do you agree with the above suggestions and can we close this now?

**Comment by imiric** [comment]
Closing this. If the approach mentioned above is insufficient we'll open another issue.
