### ISSUE TITLE
Remove the call to goja runtime from `elementHandle.newPointerAction`

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#1170]
# What

Can [elementHandle.newPointerAction](https://github.com/grafana/xk6-browser/blob/5f754c2c2252896016fd77d1fd3234a795049a0e/common/element_handle.go#L1407-L1492) be de-gojafied? All `click` APIs use it.

# How

After #1189, there's only one method to de-gojafy: `ElementHandle.offsetPosition`.

```[tasklist]
### Tasks
- [ ] #1217
- [ ] grafana/k6#3603
```

**Comment by inancgumus** [comment]
Closed by #1170.
