### ISSUE TITLE
Refactor goja runtime value parsing out of `page.goBack` promise

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1178]
# What

Refactor the parsing of the option out of the promise and into the mapping layer for `page.goBack`.

# Why

This will help avoid a scenario where more than one off main goja thread goroutine (i.e., promise) is run concurrently, which could try to access the goji runtime concurrently and cause a panic.

# How

```[tasklist]
### Tasks
- [ ] PR
- [ ] Add to release notes
```

**Comment by ankur22** [comment]
Closing since the method is unimplemented.
