### ISSUE TITLE
Generalize `page.on` events

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#1227]
### What

Generalize `page.on` events architecture.

### Why

So that [new events](https://github.com/grafana/xk6-browser/issues/1460) can easily be added to the existing code.

```[tasklist]
### Tasks
- [ ] #1473
- [ ] #1474
- [ ] #1477
- [ ] #1478
- [ ] #1475
- [ ] #1479
- [x] Update k6 release notes and tasks
```

**Comment by inancgumus** [comment]
I've changed this issue's title to focus on the generalization of `page.on` as the total work is lengthy. Please revert if you think otherwise.

**Comment by ankur22** [comment]
During the [PR](https://github.com/grafana/xk6-browser/pull/1456) to add `page.on('metric')` helpful comments were added which identified areas that could be refactored to work with generics:

- https://github.com/grafana/xk6-browser/pull/1456#discussion_r1786277948
- https://github.com/grafana/xk6-browser/pull/1456#discussion_r1786278776
- https://github.com/grafana/xk6-browser/pull/1456#discussion_r1786282485
- https://github.com/grafana/xk6-browser/pull/1456#discussion_r1786285905
- https://github.com/grafana/xk6-browser/pull/1456#discussion_r1786291372
- https://github.com/grafana/xk6-browser/pull/1456#discussion_r1786332552
- Another idea instead of generics: https://github.com/grafana/xk6-browser/pull/1456#issuecomment-2392410774
