### ISSUE TITLE
Span duplication on tracing ingestion

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1230]
### What?

@DefCon-007:

> The http endpoints directly proxy tempo, so I guess duplication may happen at ingestion time in the browser itself.

* TraceID: 1f104d305b61f1ef3b5f91511a089b13

* Test Run ID (staging): 166704

See @w1kman's internal message for details.

Version: k6 0.49

### Tasks

```[tasklist]
### Tasks
- [ ] PR
- [ ] Update the k6 release notes
```

**Comment by w1kman** [comment]
Seems to be an issue only when I have more than one browser VU.
- 100% of the time, it works with 1 VU
- 100% of the time, it DOESNT work with 2 VUs

**Comment by ankur22** [comment]
This was fixed thanks to https://github.com/grafana/xk6-browser/pull/1219 🎉
