### ISSUE TITLE
TestTracing integration test is flakey

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#1231]
### Brief summary

When the integration tests are ran in CI, the workflow often fails on one of the [TestTracing](https://github.com/grafana/xk6-browser/blob/af54d56920a7f52b1e647c09b8fc3de3d870793f/tests/tracing_test.go#L54), specifically the [web_vital](https://github.com/grafana/xk6-browser/blob/af54d56920a7f52b1e647c09b8fc3de3d870793f/tests/tracing_test.go#L111) sub test.

When this test fails we can usually rerun the failed workflow and the test will pass the second time round, so it's flakey. It would be good if this wasn't the case so that it gives us confidence in our tests and workflows, as well as making it easier to contribute to for external contributors.

### xk6-browser version

fcc7f9e5f45b099d8516cb7cc38662b9110b3c23

### OS

NA

### Chrome version

NA

### Docker version and image (if applicable)

NA

### Steps to reproduce the problem

Run the test in CI, e.g.: https://github.com/grafana/xk6-browser/actions/runs/8138217177/job/22238484745?pr=1228

### Expected behaviour

The integration test passes.

### Actual behaviour

It fails with:

```bash
--- FAIL: TestTracing (3.71s)
    tracing_test.go:161: 
        	Error Trace:	/home/runner/work/xk6-browser/xk6-browser/tests/tracing_test.go:161
        	Error:      	Received unexpected error:
        	            	"web_vital" span was not found
        	Test:       	TestTracing
```

**Comment by inancgumus** [comment]
Dup? https://github.com/grafana/xk6-browser/issues/1150

**Comment by ankur22** [comment]
Close as it's duplicate.

**Comment by inancgumus** [comment]
@ankur22  I would amend the content in this one to #1150, as this one is more descriptive. Happy to do it myself.

**Comment by ankur22** [comment]
> @ankur22 I would amend the content in this one to https://github.com/grafana/xk6-browser/issues/1150, as this one is more descriptive. Happy to do it myself.

Yes, please, thank you!
