### ISSUE TITLE
Convert Touchscreen.tap() to async

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#1251]
We want to convert the `touchscreen.tap` API from being synchronous to async (promisify). This will include:

1. De-gojafying the tap method in the common package.
2. Move the goja code into the mapping layer.
3. Wrap the call to `touchscreen.tap` from the mapping layer in a promise.

Related Issue: https://github.com/grafana/xk6-browser/issues/428
```[tasklist]
### Tasks
- [ ] #1265
- [ ] #1268
- [ ] grafana/k6-DefinitelyTyped#36
- [ ] grafana/k6-docs#1564
- [ ] grafana/k6#3723
```

**Comment by inancgumus** [comment]
The doc updates will continue in #1293.
