### ISSUE TITLE
Migrate Response APIs to async

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1309]
```[tasklist]
### Tasks
- [ ] #1364
- [ ] grafana/k6-docs#1613
- [ ] https://github.com/grafana/k6-DefinitelyTyped/pull/55
- [ ] Release Notes
```

---

## What

Migrate the following APIs according to the How section in #428:

| Class | Method | Current k6 Return | PW return |
| ---- | ---- | ---- | ---- |
|Response|allHeaders|Record<string,string>|Promise<{[key:string]:string;}>|
|Response|body|ArrayBuffer|Promise<Buffer>|
|Response|headerValue|string\|null|Promise<null\|string>|
|Response|headerValues|string[]|Promise<Array<string>>|
|Response|headersArray|Array<{name:string;value:string}>|Promise<Array<{name:string;value:string;}>>|
|Response|json|any|Promise<Serializable>|
|Response|securityDetails|SecurityDetailsObject\|null|Promise<null\|{issuer?:string;protocol?:string;subjectName?:string;validFrom?:number;validTo?:number;}>|
|Response|serverAddr|{ipAddress:string;port:number}\|null|Promise<null\|{ipAddress:string;port:number;}>|
|Response|size|{body:number;headers:number}|not found in Playwright|

For details on the Why and How, check the overarching issue in #428.

**Comment by allansson** [comment]
The type defintions for this are already async.
