### ISSUE TITLE
Panic with `we either navigate top level or have old version of the navigated frame`

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#1341]
### Brief summary

When navigating through certain websites, in some cases an error `we either navigate top level or have old version of the navigated frame` is reported which stops the test iteration. At the moment it's not clear why this occurs, but in the investigation so far we have found that the `frame` in question that is causing this panic isn't being tracked by k6 browser.

There are two ways in which a new `frame` is tracked by k6 browser:
1. Chrome tells us that a [frame is attached](https://github.com/grafana/xk6-browser/blob/ae847603ca332e4809e6a2af3845308a8245f109/common/frame_session.go#L256) (this is where we expect a CDP message);
2. We attach to the frame(s) by getting the [existing frame tree.](https://github.com/grafana/xk6-browser/blob/ae847603ca332e4809e6a2af3845308a8245f109/common/frame_session.go#L409-L412)

We have explored the CDP requests that are made between k6 browser and chrome, but we do not see a `frameAttached` event being sent from Chrome, but we can see that the `frameTree` does contain a reference to the new frame as a child.

### xk6-browser version

v1.5.1

### OS

NA

### Chrome version

NA

### Docker version and image (if applicable)

NA

### Steps to reproduce the problem

Run the script that is causing this issue to replicate the issue.

### Expected behaviour

Script passes with no issues.

### Actual behaviour

Panics with `we either navigate top level or have old version of the navigated frame`.
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/xk6-browser/pull/1346
- [ ] Release notes
- [ ] https://github.com/grafana/xk6-browser/issues/1347
```

**Comment by ankur22** [comment]
I think I have a better idea of what is happening.

1. We have the page, which has a frame and a session.
2. The page has an iframe, which is first attached with [page.frameAttached](https://github.com/grafana/xk6-browser/blob/ae847603ca332e4809e6a2af3845308a8245f109/common/frame_session.go#L736) CDP from Chrome.
3. Eventually we get a [target.attachTarget](https://github.com/grafana/xk6-browser/blob/ae847603ca332e4809e6a2af3845308a8245f109/common/frame_session.go#L891) for the iframe, but a new frameSession is also created.
4. Now we start to receive CDP requests from both the original session and new session for the iframe.
5. We finally receive a [frameDetached](https://github.com/grafana/xk6-browser/blob/0654e7a7bd0ae5d75351e1ea2b187d9ecd6c9f31/common/frame_manager.go#L165) CDP event of type "swap" from chrome for the iframe on the original session (not the new session).
6. We remove the [child frames](https://github.com/grafana/xk6-browser/blob/0654e7a7bd0ae5d75351e1ea2b187d9ecd6c9f31/common/frame_manager.go#L181).
[navigation error](https://github.com/grafana/xk6-browser/blob/0654e7a7bd0ae5d75351e1ea2b187d9ecd6c9f31/common/frame_manager.go#L232) since the child frame was removed.

I'm not 100% sure how to handle the CDP events incoming from different sessions for the same frame, but I think we can check to see if the incoming detach event's `sessionId` matches the `frame`'s `sessionId`, and if they don't match we ignore the event.

Playwright does something similar to what i'm proposing, well, they just check to see if the [frame exists](https://github.com/microsoft/playwright/blob/20a23b34850723ffa187a8f54a5ce6b36e33ac9b/packages/playwright-core/src/server/chromium/crPage.ts#L682) with a session.

Puppeteer seems to [ignore the swap](https://github.com/puppeteer/puppeteer/blob/f375267e790f61ee2a93d1f2811bef7539fc58d4/packages/puppeteer-core/src/cdp/FrameManager.ts#L435) frameDetach events completely, as in they don't seem to remove any frames :shrug:

**Comment by inancgumus** [comment]
@ankur22 

👍 Makes sense.

> Puppeteer seems to [ignore the swap](https://github.com/puppeteer/puppeteer/blob/f375267e790f61ee2a93d1f2811bef7539fc58d4/packages/puppeteer-core/src/cdp/FrameManager.ts#L435) frameDetach events completely, as in they don't seem to remove any frames 🤷

Side note: When I look into the Puppeteer's code, they seem to be doing some actions for the frame-swapped events. [This](https://github.com/puppeteer/puppeteer/blob/d963fcdd80dbcf26fc6e169917ddd18e7a751f4f/packages/puppeteer-core/src/cdp/LifecycleWatcher.ts#L224-L265) and [this](https://github.com/puppeteer/puppeteer/blob/d963fcdd80dbcf26fc6e169917ddd18e7a751f4f/packages/puppeteer-core/src/cdp/Frame.ts#L73-L77).

**Comment by ankur22** [comment]
> Side note: When I look into the Puppeteer's code, they seem to be doing some actions for the frame-swapped events. [This](https://github.com/puppeteer/puppeteer/blob/d963fcdd80dbcf26fc6e169917ddd18e7a751f4f/packages/puppeteer-core/src/cdp/LifecycleWatcher.ts#L224-L265) and [this](https://github.com/puppeteer/puppeteer/blob/d963fcdd80dbcf26fc6e169917ddd18e7a751f4f/packages/puppeteer-core/src/cdp/Frame.ts#L73-L77).

Thanks for the links. Yeah, i still don't see them removing the frames, so i feel the solution we're going with (at least for now) is a good one. We maybe have to change it if we find another edge case with iframe.

**Comment by inancgumus** [comment]
Yes, our solution is fine. Just wanted to give a heads-up about the future
changes.
