### ISSUE TITLE
Parameterise the HTTP request for uploading screenshots to a remote location

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#1342]
### What?

At the moment we can setup almost everything required to upload a screenshot to a remote location:

1. presignedURLGetter (used to retrieve the)
2. the folder name (base path)
3. Headers

What we do not have is the HTTP request method. It would be good if the http request was parameterised too (for both the presignedURLGetter and the presignedURL).

### Why?

This will avoid having to make a change to k6 browser and wait for a release to change the screenshot upload remote URL characteristics.

### How?

1. The http request method will need to be added to an env var, maybe just append it to the existing env var (`K6_BROWSER_SCREENSHOTS_OUTPUT`).
2. For the presignedURL itself, it would be good to have the request method type returned with the presigned url.

### Tasks

```[tasklist]
### Tasks
- [ ] PR
- [ ] Update the k6 release notes
```

**Comment by inancgumus** [comment]
Closing this as it's done by #1419. Regarding the `presignedURL` HTTP method, it should only be POST, as that is how AWS and the new v2 screenshot protocol work.
