### ISSUE TITLE
how to use dynamic content inside page.evaluate

### ISSUE THREAD

**Issue by ASaiAnudeep** [grafana/xk6-browser#1427]
### Brief summary

I'm not able to use `page.evaluate` with variables inside it.

```js
const operation_name = `login-end`
await page.evaluate(() => window.performance.mark(operation_name));
```

Facing the following error

```log
ERRO[0007] Uncaught (in promise) evaluating JS: ReferenceError: operation_name is not defined
    at __xk6_browser_evaluation_script__:1:32  executor=constant-vus scenario=ui
```

### k6 version

v0.53.0 (go1.22.6, darwin/arm64)

### OS

macOS 14.6.1

### Steps to reproduce the problem

```js
const operation_name = `login-end`
await page.evaluate(() => window.performance.mark(operation_name));
```

### Expected behaviour

I should be able to use variables inside evaluate function.

### Actual behaviour

I am not able to use variables inside evaluate function.

**Comment by ankur22** [comment]
Hi,

Thanks for opening an issue. We prefer that you open a new thread in our [community forum](https://community.grafana.com/c/grafana-k6/k6-browser/79) first. From there we can diagnose the issue and if needed open a bug/feature request here.

However, i'm happy to assist you on this. You need to pass in `operation_name` as an argument to the `page.evaluate` function like so:

```js
const operation_name = `login-end`
await page.evaluate((opN) => window.performance.mark(opN), operation_name);
```

Here's the documentation on [page.evaluate](https://grafana.com/docs/k6/latest/javascript-api/k6-browser/page/evaluate/).

I'm going to close this issue. If you have any further problems then head over to our community forum and we will help from there.

Hope that helps,
Ankur

**Comment by ASaiAnudeep** [comment]
Thank you @ankur22 . I overlooked the documentation.
