### ISSUE TITLE
Add the ability to filter by request type in `page.on('metric')`

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#1487]
### Feature Description

We have `page.on('metric')` which allows us to group metrics when a URL match is found. The issue arises when the website under test makes different types of requests using the same URL, for example a GET to api/cart, and a POST to api/cart. In this case it's not going to be useful to group the same request together as the behaviour of them will be different.

What would be useful is to be able to filter/group also by the request type.

### Suggested Solution (optional)

A possible solution is to extend the existing API so that it can also take a `type` field. If the `type` field isn't present, it will assume that all requests are to be grouped regardless of the type. If a `type` field is present it will take that into account:

```js
  page.on('metric', (metric) => {
    metric.tag({
      urls: [
        {url: /^https:\/\/test\.k6\.io\/\?q=[0-9a-z]+$/, type:'GET', name:'test'},
      ]
    });
  });
```

### Already existing or connected issues / PRs (optional)

https://github.com/grafana/xk6-browser/issues/371
https://github.com/grafana/xk6-browser/issues/1434

```[tasklist]
- [ ] https://github.com/grafana/xk6-browser/pull/1489
- [ ] https://github.com/grafana/xk6-browser/pull/1490
- [x] Add to release notes: https://github.com/grafana/k6/commit/da3a11112ce4cfb2f7bc9544ae9199a40df7be53
- [ ] https://github.com/grafana/k6-DefinitelyTyped/pull/73
- [ ] https://github.com/grafana/k6-docs/pull/1807
```

**Comment by inancgumus** [comment]
The suggested solution is mixing the tag name and properties. It was fine when there was only `url` and `name`. I believe the API might be less confusing if it would group these `url` by a `name` instead of having `name` as another property. Maybe something like:

```javascript
page.on('metric', metric => {
  metric.tag({
    name: 'tests',
    urls: [
      {url: /^https:\/\/test\.k6\.io\/\?q=[0-9a-z]+$/, type:'GET'},
    ]
  }, {
    name: 'other',
    urls: [
      {url: /^https:\/\/test\.k6\.io\/\?q=[0-9a-z]+$/, type:'POST'},
      {url: /^https:\/\/foo\.com/, type:'GET'},
    ]
  });
});
```

**Comment by ankur22** [comment]
@inancgumus I can see where you are coming from, I like this approach 👍
