### ISSUE TITLE
'screen' property ignored/always set to the same values as 'viewport'

### ISSUE THREAD

**Issue by tom-miseur** [grafana/xk6-browser#182]
On Windows and launching a `chromium` instance, with the following browser context options:

```javascript
  const context = browser.newContext({
    screen: {width: 1920, height: 1080},
    viewport: {width: 800, height: 600},
  });
````

I expect the browser window to be larger than the `viewport`, however that does not appear to be the case; instead, the browser dimensions appear to always match those of the `viewport`, which can lead to elements not being visible and therefore not being "actionable".

An example where this presents a problem:

When navigating to http://ecommerce.test.k6.io, there is a footer that remains outside of view until the browser window is manually expanded.

As launched using `viewport: {width: 800, height: 600}`:

![image](https://user-images.githubusercontent.com/37644300/148597558-58e8864f-cb01-44a5-8e4a-928151b2af3f.png)

The browser window itself is 800*600, including the browser window at the top.

Manually increasing the browser window dimensions reveals a scrollbar on the right and the footer along the bottom:

![image](https://user-images.githubusercontent.com/37644300/148597873-71f3fd07-f0cd-4428-967f-13c0c9a10322.png)

The extra height can be attributed to the height of the browser menu:

![image](https://user-images.githubusercontent.com/37644300/148598786-bae6a957-c86a-459c-b0a1-04501799e950.png)

If the browser window isn't expanded, actions against the hidden footer silently fail. It also causes problems with `scrollIntoView`/`scrollIntoViewIfNeeded`; with the below script, the "Add to Cart" `click` fails to bring the element fully into view.

```javascript
import launcher from 'k6/x/browser';
import { check, group, sleep } from 'k6';

export default function () {
  const browser = launcher.launch('chromium', {
    headless: false,
    // slowMo: '500ms' // slow down by 500ms
  });

  const context = browser.newContext({
    screen: {width: 1920, height: 1080},
    viewport: {width: 800, height: 600},
  });

  const page = context.newPage();

  group("Navigate to Homepage", () => {
    page.goto('http://ecommerce.test.k6.io/', { waitUntil: 'networkidle' });

    page.waitForSelector('.woocommerce-result-count');
  });

  sleep(2);

  let dimensions = page.evaluate(() => {
    return { 
      clientWidth: document.documentElement.clientWidth,
      clientHeight: document.documentElement.clientHeight,
      innerWidth: window.innerWidth,
      innerHeight: window.innerHeight,
      outerWidth: window.outerWidth,
      outerHeight: window.outerHeight
    }
  });

  console.log(JSON.stringify(dimensions));

  sleep(2);

  // dismiss the demo store message
  page.click('.woocommerce-store-notice__dismiss-link');

  group("Click Product", () => {
    page.click('.woocommerce-loop-product__title', { waitUntil: 'networkidle' });

    page.waitForSelector('button[name="add-to-cart"]');
  });

  sleep(2);

  group("Click Add to Cart", () => {
    console.log("Clicking Add to Cart...");

    page.click('button[name="add-to-cart"]');

    page.waitForNavigation();

    console.log("Waiting for .woocommerce-message...");

    page.waitForSelector('.woocommerce-message');
  });

  sleep(2);

  group("View Cart", () => {
    page.click('.cart-contents', { waitUntil: 'networkidle' });

    page.waitForSelector('.woocommerce-cart-form__cart-item');
  });

  sleep(2);

  page.close();
  browser.close();
}
```

Playwright handles the browser window dimensions correctly. Omitting the call to `browser.SetWindowBounds` [here](https://github.com/grafana/xk6-browser/blob/aadc37495226dd5e8b06e0758f382213bb2a819b/common/frame_session.go#L1023-L1029) unfortunately did not cause the browser window to adjust automatically so as to display the entire `viewport`.

**Comment by inancgumus** [comment]
Thanks, this issue is actually two issues combined:

1. Adjusting the viewport accordingly
2. Clicking on hidden elements causing problems

@tom-miseur Could you please create a separate issue for the second one? And elaborate how Playwright acts when clicking on hidden elements in this case?

Thanks!

**Comment by tom-miseur** [comment]
Actually, I'm no longer able to reproduce the add-to-cart click failing to scroll the element fully into view, not even with `main`. I'm seeing it bring the button into view, even regardless of whether the viewport is fully displayed. I'm not sure what's changed... Will keep an eye on it.

BTW #183 works great!

**Comment by inancgumus** [comment]
> I'm no longer able to reproduce the add-to-cart click failing to scroll the element fully into view

You may have an updated Chrome version?

> BTW #183 works great!

🤩  Good to hear!

**Comment by inancgumus** [comment]
Tom can no longer reproduce this problem, and everything works correctly now. #187 has solved these problems. @tom-miseur, I'm closing this issue, and you can reopen it if you like.

**Comment by tom-miseur** [comment]
Thanks @inancgumus ! Should we remove `screen`, given that it doesn't appear to be doing anything (at least not on Windows)?

**Comment by inancgumus** [comment]
You're welcome :)

[Playwright documentation](https://playwright.dev/docs/api/class-browser/#browser-new-context-option-screen) says:
> `screen` Emulates consistent window screen size available inside web page via window.screen.
> Is only used when the viewport is set.
>
> width <number> page width in pixels.
> height <number> page height in pixels.

Similarly, the `screen` property has an effect on `screenWidth` and `screenHeight`. I experimented with different variations of `screen` and `viewport` options, here are the results:

```js
const context = browser.newContext()

// Output:
{"screenWidth":1280,"screenHeight":720,"clientWidth":1280,"clientHeight":720,"innerWidth":1280,"innerHeight":720,"outerWidth":1280,"outerHeight":799}
```

```js
const context = browser.newContext({
  screen: {width: 1920, height: 1080},
});

// Output:
{"screenWidth":1920,"screenHeight":1080,"clientWidth":1280,"clientHeight":720,"innerWidth":1280,"innerHeight":720,"outerWidth":1280,"outerHeight":799}
```

```js
const context = browser.newContext({
  screen: {width: 1920, height: 1080},
  viewport: {width: 3840, height: 2160},
});

// Output:
{"screenWidth":1920,"screenHeight":1080,"clientWidth":3840,"clientHeight":2160,"innerWidth":3840,"innerHeight":2160,"outerWidth":3840,"outerHeight":1415}
```

```js
const context = browser.newContext({
  viewport: {width: 3840, height: 2160},
});

// Output:
{"screenWidth":1280,"screenHeight":720,"clientWidth":3840,"clientHeight":2160,"innerWidth":3840,"innerHeight":2160,"outerWidth":3840,"outerHeight":1415}
```
