### ISSUE TITLE
Migrate to a k6/js.modules.Module (ModulesV2)

### ISSUE THREAD

**Issue by olegbespalov** [grafana/xk6-browser#194]
## What?

In the k6 [we deprecated](https://github.com/grafana/k6/issues/2344), the usage of the old modules API and in the middle of the process of the migration to a new [ModulesV2 API](https://pkg.go.dev/go.k6.io/k6/js/modules#Module).

To do that, we need to clean up the usages of the deprecated methods:

```code
grep --exclude-dir=vendor -ER "With(State|ScenarioState|ExecutionState|InitEnv|Runtime|Engine)\(" ./
./common/remote_object_test.go:		ctx := k6common.WithRuntime(context.Background(), rt)
./common/remote_object_test.go:		ctx := k6common.WithRuntime(context.Background(), rt)
./common/remote_object_test.go:		ctx := k6common.WithRuntime(context.Background(), rt)
./common/remote_object_test.go:		ctx := k6common.WithRuntime(context.Background(), rt)
./common/remote_object_test.go:		ctx := k6common.WithRuntime(context.Background(), rt)
./common/request_test.go:	ctx := k6common.WithRuntime(context.Background(), rt)
./tests/test_browser.go:	ctx = k6lib.WithState(ctx, state)
./tests/test_browser.go:	ctx = k6common.WithRuntime(ctx, rt)

grep --exclude-dir=vendor -Ri "common.Bind" ./
./common/browser_context.go:					exported := k6common.Bind(rt, p, &b.ctx)
./tests/test_browser.go:		err = rt.Set("http", k6common.Bind(rt, new(k6http.GlobalHTTP).NewModuleInstancePerVU(), &ctx))
```

A good starting point can be our guide [Create an extension](https://k6.io/docs/extensions/guides/create-an-extension/#advanced-javascript-extension).

## Why?

The traditional approach of initializing JS modules involves calling common.Bind() on any objects that need to be exposed to JS. This method has a few technical issues we want to improve and isn't flexible enough to implement new features like giving extensions access to internal k6 objects.

**Comment by mstoykov** [comment]
This seems to have been completely closed with https://github.com/grafana/xk6-browser/pull/286
