### ISSUE TITLE
Update k6 usage examples for Windows

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#199]
One of our users [had difficulty](https://community.k6.io/t/erro-0000-unknown-module-k6-x-browser/2766/11) installing and using xk6-browser on Windows. We better improve our documentation for Windows.

**Comment by mdcruz** [comment]
Closing as this is added as part of https://k6.io/docs/javascript-api/xk6-browser/get-started/installation/ and https://k6.io/docs/javascript-api/xk6-browser/get-started/running-xk6-browser/
