### ISSUE TITLE
Closing the browser window hangs the test

### ISSUE THREAD

**Issue by imiric** [grafana/xk6-browser#20]
If the user closes the browser window while a test is running, the test will continue and never exit, and k6 has to be killed with `Ctrl+C` or another signal.

This is not something that users should do, but [since it's possible](https://i.imgur.com/X17puIB.gif), we should handle it gracefully. :)

Presumably we're stuck in a goroutine waiting for messages from the browser, but there should be a "closing" event we can detect, either some CDP event, or just that the WebSocket connection was closed, in case the browser crashes. Maybe try reconnecting as well?

So the test should probably stop with an error that we lost connection to the browser, or that it was closed, something to that effect.

**Comment by inancgumus** [comment]
@imiric, Can you check if this issue is still relevant after recent fixes?

**Comment by imiric** [comment]
Sure, just tested it, and we're detecting context cancellations properly now, which will print an error, but the test doesn't hang anymore :tada:

So yeah, closing this. :+1:
