### ISSUE TITLE
page.waitForNavigation causes time out

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#226]
Please see https://github.com/grafana/xk6-browser/issues/200#issuecomment-1033194052 and https://github.com/grafana/xk6-browser/issues/200#issuecomment-1033198708 for details.

> Adding page.waitForNavigation(); in place of page.waitForSelector('div.cb-content'); caused a waitForFrameNavigation timed out after 30s.

<details>
<summary>Script Source</summary>

```js
import launcher from 'k6/x/browser';
import { group, sleep } from 'k6';

export default function () {
  const browser = launcher.launch('chromium', {
    headless: false,
  });

  const context = browser.newContext({
  });

  const page = context.newPage();

  group("Navigate to Homepage", () => {
    page.goto('https://trollflix.com'); // without the below waitForSelector, the page.$$ expression returns a length of 0

    page.waitForSelector('div.cb-content'); // required here even if I were to use waitUntil: 'networkidle' above
    
    // grab the number of displayed videos (should be 12)
    const videoCount = page.$$('div.cb-content').length;
    console.log(`Found ${videoCount} in page`);
  });

  sleep(2);

  group("Filter by Gaming", () => {
    page.hover('#hn-categories');

    sleep(1);

    // without the below waitForSelector, the page.$$ expression returns a length of 0 (interestingly, not the previous value - 12 - so the expression was evaluated after the page partially refreshed)
    page.$('//div[text()="Gaming"]').click(); 

    page.waitForSelector('div.cb-content'); // waiting for the div here ensures the videoCount updates as expected

    // grab the number of displayed videos (should be 2)
    const videoCount = page.$$('div.cb-content').length;
    console.log(`Found ${videoCount} in page`);
  });
}
```

</details>

**Comment by imiric** [comment]
I ran into this as well while testing the staging app. Looking into it.

It could be considered part of #200 though.

**Comment by imiric** [comment]
I've been looking into this issue, and it seems to happen when the navigation happens within the same document, e.g. by using the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API).

In these cases the [`Page.navigatedWithinDocument` event](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-navigatedWithinDocument) is received, for which [we properly emit the internal `NavigationEvent`](https://github.com/grafana/xk6-browser/blob/917b83ef14b3e2075f92c092163c47e359883a6a/common/frame_manager.go#L354), but in `WaitForFrameNavigation()` we also wait for a `FrameAddLifecycle` event:
https://github.com/grafana/xk6-browser/blob/917b83ef14b3e2075f92c092163c47e359883a6a/common/frame_manager.go#L725-L736

... which is never emitted in these internal navigations, so the wait times out.

I'm still not sure what the correct fix would be, and will keep investigating.
