### ISSUE TITLE
panic: unable to dispose element *runtime.ReleaseObjectParams: Cannot find context with specified id error

### ISSUE THREAD

**Issue by AleCatSS** [grafana/xk6-browser#235]
Hello,

In one of the k6 scripts I am building for testing I need the user interaction to press a button before going on with other steps.

The script works fine when I use it from my local machine but when I run it in docker I sometimes (around 90% of the time) receive the following error:

`panic: unable to dispose element *runtime.ReleaseObjectParams: Cannot find context with specified id (-32000)
running (00m23.8s), 1/1 VUs, 0 complete and 0 interrupted iterations
goroutine 209 [running]:-------------------------] 1 VUs  00m17.8s/10m0s  0/1 iters, 1 per VU
go.k6.io/k6/js/common.Throw(...)
	go.k6.io/k6@v0.36.0/js/common/util.go:36
github.com/grafana/xk6-browser/common.(*BaseJSHandle).Dispose(0xc001eb1fc0)
	github.com/grafana/xk6-browser@v0.1.3/common/js_handle.go:90 +0x2e6
github.com/grafana/xk6-browser/common.(*Frame).detach(0xc001728680)
	github.com/grafana/xk6-browser@v0.1.3/common/frame.go:306 +0x1cc
github.com/grafana/xk6-browser/common.(*FrameManager).removeFramesRecursively(0xc0019b6000, 0xc001728680)
	github.com/grafana/xk6-browser@v0.1.3/common/frame_manager.go:418 +0x39a
github.com/grafana/xk6-browser/common.(*FrameManager).frameDetached(0xc0019b6000, 0xc000754560, 0x20)
	github.com/grafana/xk6-browser@v0.1.3/common/frame_manager.go:196 +0x1ba
github.com/grafana/xk6-browser/common.(*FrameSession).onFrameDetached(0xc003967950, 0xc000754560, 0x20, 0x151c3d6, 0x6)
	github.com/grafana/xk6-browser@v0.1.3/common/frame_session.go:625 +0x1e5
github.com/grafana/xk6-browser/common.(*FrameSession).initEvents.func1(0xc003967950)
	github.com/grafana/xk6-browser@v0.1.3/common/frame_session.go:263 +0x488
created by github.com/grafana/xk6-browser/common.(*FrameSession).initEvents
	github.com/grafana/xk6-browser@v0.1.3/common/frame_session.go:237 +0x1ca
make: *** [Makefile:95: benchmark-rps] Error 2`

This happens when I try to click the button. 

The button is in a nested iframe inside another iframe and I make sure to wait that the button is there before trying to press it. 

In the docker I build the k6 executable with:

`xk6 build v0.36.0 --output xk6-browser --with github.com/grafana/xk6-browser`

and I also install Chronium with:

`apk add --no-cache  chromium --repository=http://dl-cdn.alpinelinux.org/alpine/latest-stable`

Any idea what may be causing this and how to solve it?

Thank you

**Comment by inancgumus** [comment]
Hi @AleCatSS,

Thanks for reporting this issue.

Could you try installing xk6-browser as explained in the README? This step probably won't help, but it is worth giving it a try:

```
xk6 build v0.35.0 --output xk6-browser --with github.com/grafana/xk6-browser
```

It seems like frames in the web page change before we release the element. It will also be helpful for us to diagnose the issue better if you could share your script and the web page (or part of its source if it's private).

Thanks.

**Comment by AleCatSS** [comment]
Hello ,

thank you very much for looking into this problem.
I tried building the executable with:

`xk6 build v0.35.0 --output xk6-browser --with github.com/grafana/xk6-browser`

the result is the same unfortunately.

After loading the page and waiting some seconds to be sure that everything is loaded, my script does this:

`       const mainFrameHandle = page.$('iframe[name*="MAIN-FRAME-NAME"]');
        const mainFrame = mainFrameHandle.contentFrame();

        const subFrameHandler = mainFrame.$(
            'iframe[name="SUB-FRAME-NAME"]'
        );

        const subFrame = subFrameHandler.contentFrame();

        subFrame.evaluate(() => {
            document.getElementById('BUTTON-ID').click();
            return true;
        });`

The error appears at the last operation.

I wonder what is causing the difference between running the script locally and in docker, locally it works 100% of the time.

Thank you

**Comment by inancgumus** [comment]
Thank you. Is it possible to share the web page as well? Btw, I also wonder about your local Chrome version? Do you have Chromium installed as well?

**Comment by AleCatSS** [comment]
Unfortunately I cannot share the page as is not public. About my local settings, when I run the test it spins up the local Chrome (Version 98.0.4758.80 (Official Build) (x86_64)) on my machine (MacOS Big Sur 11.6.3). I'll do some tests matching the two versions if they are different and post back the results.
Thank you!

**Comment by AleCatSS** [comment]
To add more context, in the docker image I'm using the Alpine chromium package which uses chromium version 93.0.4577.82. Not sure if this version difference can explain the issue.

**Comment by inancgumus** [comment]
Yes, it might and it should if that's the only difference between your docker and local environment.

**Comment by inancgumus** [comment]
Closed for now, please reopen if it rehappens.
