### ISSUE TITLE
Data race in TestWaitForFrameNavigationWithinDocument: Page.WaitForNavigation

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#273]
See: https://github.com/grafana/xk6-browser/issues/254#issuecomment-1060380139

Related: [#254: Data race in TestWaitForFrameNavigationWithinDocument: NavigateFrame](https://github.com/grafana/xk6-browser/issues/254)

**Comment by imiric** [comment]
This issue should be solved by #271. See https://github.com/grafana/xk6-browser/issues/271#issuecomment-1063929216.
