### ISSUE TITLE
Remove deprecated usage of k6 context-based utils

### ISSUE THREAD

**Issue by imiric** [grafana/xk6-browser#275]
Context-based utils were recently [deprecated in k6](https://github.com/grafana/k6/commit/335d99cbb30bbb45921d63104298a3a4f6808ba8), and will be removed in v0.38.0 (https://github.com/grafana/k6/issues/2385). Currently we get a `staticcheck` linter failure of `SA1019: k6common.GetRuntime is deprecated: Use modules.VU for get the Runtime.` which is good, but we should remove their usage from the extension, which currently only involves _a lot_ of `GetRuntime()`.

`rg 'k6common\.Get' | wc -l` outputs `156`, and `rg '\.GetRuntime' | wc -l` `157` (there's one usage of `common.GetRuntime()`.

A tentative approach of doing this is being explored in #268, which involves attaching `VU` to our internal context, but other ideas are welcome.

**Comment by inancgumus** [comment]
An interim approach is explained [here](https://github.com/grafana/xk6-browser/pull/268#discussion_r823459895) until #271 lands.

**Comment by imiric** [comment]
This was done in #286.
