### ISSUE TITLE
Pressing keys in combination is not supported

### ISSUE THREAD

**Issue by imiric** [grafana/xk6-browser#285]
On current `main` (12eeeb5) the following test:

https://github.com/grafana/xk6-browser/blob/61fb0c26e29d1b95209ab1080e49f08875b8e8d6/tests/keyboard_test.go#L72-L94

... fails with:
```
panic: cannot press key: cannot do key down: "Shift+KeyA" is not a valid key for layout "us" [recovered]
        panic: cannot press key: cannot do key down: "Shift+KeyA" is not a valid key for layout "us"

goroutine 67 [running]:
testing.tRunner.func1.2({0x1850c60, 0xc00059fef0})
        /home/ivan/.local/share/go/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
        /home/ivan/.local/share/go/src/testing/testing.go:1212 +0x3b6
panic({0x1850c60, 0xc00059fef0})
        /home/ivan/.local/share/go/src/runtime/panic.go:1047 +0x266
go.k6.io/k6/js/common.Throw(0xc0005d7cc0, {0x1a7c8c0, 0xc0005ba520})
        /home/ivan/Projects/grafana/xk6-browser/vendor/go.k6.io/k6/js/common/util.go:36 +0x79
github.com/grafana/xk6-browser/common.k6Throw({0x1a9a780, 0xc00057c090}, {0x189cd1d, 0x14}, {0xc0005d7de8, 0x1, 0x1})
        /home/ivan/Projects/grafana/xk6-browser/common/helpers.go:214 +0x22f
github.com/grafana/xk6-browser/common.(*Keyboard).Press(0xc0003561e0, {0x188ec4a, 0xa}, {0x0, 0x0})
        /home/ivan/Projects/grafana/xk6-browser/common/keyboard.go:91 +0x1e5
github.com/grafana/xk6-browser/tests.TestKeyboardPress.func4(0x0)
        /home/ivan/Projects/grafana/xk6-browser/tests/keyboard_test.go:81 +0x12e
testing.tRunner(0xc0001f21a0, 0xc0001ee140)
        /home/ivan/.local/share/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
        /home/ivan/.local/share/go/src/testing/testing.go:1306 +0x727
```

This is more of a feature request than a bug, since [Playwright supports this](https://playwright.dev/docs/api/class-keyboard).

**Comment by ankur22** [comment]
I've played around with this functionality in playwright and read the docs, [which states that](https://playwright.dev/docs/api/class-keyboard#keyboard-down):

> Holding down Shift will type the text that corresponds to the key in the upper case.
> 
> If key is a single character, it is case-sensitive, so the values a and A will generate different respective texts.
> 
> If key is a modifier key, Shift, Meta, Control, or Alt, subsequent key presses will be sent with that modifier active. To release the modifier key, use [keyboard.up(key)](https://playwright.dev/docs/api/class-keyboard#keyboard-up).

So i think the following:

```
 	kb.Press("Shift+KeyA", nil) 
 	kb.Press("Shift+b", nil) 
 	kb.Press("C", nil) 
 	kb.Press("d", nil) 
```

Should output `ABCd`, but in playwrigth (aswell as in the test above) the output is `AbCd`.

Can someone explain what i'm missing or where the discrepancy is?

**Comment by ankur22** [comment]
I left a bug report to help clarify what the logic is with PW here: https://github.com/microsoft/playwright/issues/14501

They've responded, so now it makes sense:
* `Shift+KeyA` -> `A`
* `KeyA` -> `a`
* `A` -> `A`
* `a` -> `a`
* `Shift+A` -> `A`
* `Shift+a` -> `a`

The `Shift` modifier will only change the case of a character if `KeyA` - `KeyZ` is used
