### ISSUE TITLE
Run on headless server

### ISSUE THREAD

**Issue by leledumbo** [grafana/xk6-browser#297]
We need to generate a load our local computers are incapable of, but we have a Kubernetes instance that can. However, providing `{ headless: false }` is insufficient, as chrome still expects an X server to be running.

I come across this old post: https://developers.google.com/web/updates/2017/04/headless-chrome
which should make it possible, I guess? AFAICS, looking at the code, chrome isn't launched with --headless when `{ headless: false }` is given, but some other mechanism (CMIIW), which may explain why.

**Comment by imiric** [comment]
Hi there!

> providing `{ headless: false }` is insufficient

The value needs to be `headless: true` :slightly_smiling_face:

[The `--headless` flag is indeed passed when the value is `true`.](https://github.com/grafana/xk6-browser/blob/f54363b4b1327a762d2b178fdbc9ac90801612e6/chromium/browser_type.go#L282)

With this flag Chrome doesn't require X to be running, but you still need some X libraries to be installed. See [the script we use for Ubuntu](https://github.com/grafana/xk6-browser/blob/f54363b4b1327a762d2b178fdbc9ac90801612e6/.github/bin/install_chrome_deps_linux.sh). [We run this setup in CI](https://github.com/grafana/xk6-browser/blob/f54363b4b1327a762d2b178fdbc9ac90801612e6/.github/workflows/e2e.yml), so it should work fine in Kubernetes as well.

Please post on the [community forum](https://community.k6.io/c/xk6-browser/) if you have any further questions, and create an issue here only if you're certain it's a bug or have a feature request. Thanks!

**Comment by leledumbo** [comment]
> The value needs to be headless: true

My bad, I really meant this.

> but you still need some X libraries to be installed. See [the script we use for Ubuntu](https://github.com/grafana/xk6-browser/blob/f54363b4b1327a762d2b178fdbc9ac90801612e6/.github/bin/install_chrome_deps_linux.sh). [We run this setup in CI](https://github.com/grafana/xk6-browser/blob/f54363b4b1327a762d2b178fdbc9ac90801612e6/.github/workflows/e2e.yml), so it should work fine in Kubernetes as well.

Nice! Will take a look and report back.
