### ISSUE TITLE
Invalid memory error

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#31]
I can finally reproduce this issue on my local Ubuntu VM. This needs further investigation.

```
$ go test ./tests -failfast -v -race -count=100 -run='TestLaunchOptionsSlowMo/Frame'

=== RUN   TestLaunchOptionsSlowMo
=== RUN   TestLaunchOptionsSlowMo/Frame
=== RUN   TestLaunchOptionsSlowMo/Frame/check
--- FAIL: TestLaunchOptionsSlowMo (30.22s)
    --- FAIL: TestLaunchOptionsSlowMo/Frame (30.01s)
        --- FAIL: TestLaunchOptionsSlowMo/Frame/check (30.01s)
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf6ebca]

goroutine 32 [running]:
testing.tRunner.func1.2({0x15c9820, 0x23d2fa0})
	/snap/go/8489/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/snap/go/8489/src/testing/testing.go:1212 +0x3b6
panic({0x15c9820, 0x23d2fa0})
	/snap/go/8489/src/runtime/panic.go:1047 +0x266
github.com/grafana/xk6-browser/common.(*Page).Close(0x0, {0xc0004e7b30, 0x468240})
	xk6-browser/common/page.go:299 +0x2a
panic({0x15c9820, 0x23d2fa0})
	/snap/go/8489/src/runtime/panic.go:1047 +0x266
github.com/grafana/xk6-browser/common.(*Page).MainFrame(...)
	xk6-browser/common/page.go:475
github.com/grafana/xk6-browser/common.(*Page).EvaluateHandle(0x0, {0x1924700, 0xc000054130}, {0xc00021e2c0, 0x2, 0x2})
	xk6-browser/common/page.go:376 +0x4a
github.com/grafana/xk6-browser/testutils/browsertest.AttachFrame(0xc00009c340, {0x1932230, 0x0}, {0x1723bb5, 0x6}, {0xc0000b8570, 0x21})
	xk6-browser/testutils/browsertest/utils.go:51 +0x202
github.com/grafana/xk6-browser/tests.testFrameSlowMoImpl(0x0, 0xc00009c340, 0x1775b70)
	xk6-browser/tests/launch_options_slowmo_test.go:270 +0x196
github.com/grafana/xk6-browser/tests.TestLaunchOptionsSlowMo.func2.1(0x0)
	xk6-browser/tests/launch_options_slowmo_test.go:143 +0x45
testing.tRunner(0xc00009a820, 0xc0000b1250)
	/snap/go/8489/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/snap/go/8489/src/testing/testing.go:1306 +0x727
FAIL	github.com/grafana/xk6-browser/tests	30.248s
FAIL
```

**Comment by elimatripathy** [comment]
I can also reproduce this error 
ERRO[0043] communicating with browser: websocket: close 1006 (abnormal closure): unexpected EOF  category=cdp elapsed="0 ms" goroutine=5988
ERRO[0043] process with PID 28665 unexpectedly ended: signal: killed  category=browser elapsed="1 ms" goroutine=5985
ERRO[0045] panic: runtime error: invalid memory address or nil pointer dereference
goroutine 95 [running]:
runtime/debug.Stack()
login   runtime/debug/stack.go:24 +0x65
go.k6.io/k6/js/common.RunWithPanicCatching.func1()
        go.k6.io/k6@v0.42.0/js/common/util.go:82 +0x191
panic({0x2040820, 0x31afe20})
        runtime/panic.go:884 +0x212
github.com/dop251/goja.(*Runtime).runWrapped.func1()
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/runtime.go:2409 +0xdc
panic({0x2040820, 0x31afe20})
        runtime/panic.go:884 +0x212
github.com/dop251/goja.(*vm).try.func1()
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/vm.go:626 +0x70f
panic({0x2040820, 0x31afe20})
        runtime/panic.go:884 +0x212
github.com/grafana/xk6-browser/common.(*screenshotter).screenshot(0xc0010d2888, {0x2536490?, 0xc001584a20}, 0x0, 0xc0010d2738, {0x22258fb, 0x3}, 0x0, 0xc000809200?, {0xc000817e10, ...})
        github.com/grafana/xk6-browser@v0.7.0/common/screenshotter.go:139 +0x385
github.com/grafana/xk6-browser/common.(*screenshotter).screenshotPage(0xc0010d28a8?, 0xc0086198c0, 0xc0010d28a8)
        github.com/grafana/xk6-browser@v0.7.0/common/screenshotter.go:341 +0x356
github.com/grafana/xk6-browser/common.(*Page).Screenshot(0xc0086198c0, {0x253d578?, 0xc000c474d0?})
        github.com/grafana/xk6-browser@v0.7.0/common/page.go:769 +0x13a
reflect.Value.call({0x2208560?, 0xc0086198c0?, 0x3700a68?}, {0x2225b8c, 0x4}, {0xc001840678, 0x1, 0xc0010d2fb8?})
        reflect/value.go:584 +0x8c5
reflect.Value.Call({0x2208560?, 0xc0086198c0?, 0xc000c474d0?}, {0xc001840678?, 0xc000ab16d0?, 0x203000?})
        reflect/value.go:368 +0xbc
github.com/dop251/goja.(*Runtime).wrapReflectFunc.func1({{0x253d578, 0xc008a18510}, {0xc001795c40, 0x1, 0x36}})
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/runtime.go:1952 +0x1da
github.com/dop251/goja.(*vm)._nativeCall(0xc0014e6c00, 0xc0027d4c00, 0x1)
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/vm.go:3233 +0x1e3
github.com/dop251/goja.call.exec(0x4?, 0xc0014e6c00)
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/vm.go:3205 +0x14d
github.com/dop251/goja.(*vm).run(0xc0014e6c00)
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/vm.go:495 +0x8b
github.com/dop251/goja.(*baseJsFuncObject)._call(0xc008a0c540, {0x0?, 0x0, 0x14b1978?}, {0x0?, 0x0}, {0x0?, 0x0?})
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/func.go:318 +0x3f8
github.com/dop251/goja.(*arrowFuncObject).Call(0x1fbc100?, {{0x0, 0x0}, {0x0, 0x0, 0x0}})
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/func.go:284 +0x57
github.com/dop251/goja.(*Runtime).promiseProto_finally.func2({{0x253de60, 0x3204740}, {0xc000ab1580, 0x1, 0x1}})
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/builtin_promise.go:356 +0xd5
github.com/dop251/goja.(*Runtime).callJobCallback(...)
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/runtime.go:2827
github.com/dop251/goja.(*Runtime).newPromiseReactionJob.func1.1()
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/builtin_promise.go:185 +0x105
github.com/dop251/goja.(*vm).try(0xc0014e6c00, 0x253d578?)
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/vm.go:634 +0x18a
github.com/dop251/goja.(*Runtime).newPromiseReactionJob.func1()
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/builtin_promise.go:184 +0xb8
github.com/dop251/goja.(*Runtime).leave(0xc00051e000)
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/runtime.go:2702 +0x84
github.com/dop251/goja.(*Runtime).runWrapped(0xc00051e000, 0x3700108?)
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/runtime.go:2419 +0x11f
github.com/dop251/goja.AssertFunction.func1({0x0?, 0x0?}, {0xc0010b9070?, 0x1fc8220?, 0xc00175f201?})
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/runtime.go:2368 +0x92
github.com/dop251/goja.(*Runtime).wrapPromiseReaction.func1({0x21af620?, 0xc0079fe500?})
        github.com/dop251/goja@v0.0.0-20221106173738-3b8a68ca89b4/builtin_promise.go:570 +0x97
github.com/grafana/xk6-browser/k6ext.promise.func1.1()
        github.com/grafana/xk6-browser@v0.7.0/k6ext/promise.go:46 +0x71
go.k6.io/k6/js/eventloop.(*EventLoop).Start(0xc000f9e0f0, 0xc00862d800)
        go.k6.io/k6@v0.42.0/js/eventloop/eventloop.go:171 +0x196
go.k6.io/k6/js.(*VU).runFn.func2()
        go.k6.io/k6@v0.42.0/js/runner.go:789 +0xeb
go.k6.io/k6/js/common.RunWithPanicCatching({0x2541820?, 0xc000590200?}, 0x100f3e6?, 0x2056c40?)
        go.k6.io/k6@v0.42.0/js/common/util.go:86 +0x87
go.k6.io/k6/js.(*VU).runFn(0xc000ffce40, {0x252f560, 0xc00110be40}, 0x20?, 0xc000dac300, 0xc0023768f0, {0xc002376900, 0x1, 0x1})
        go.k6.io/k6@v0.42.0/js/runner.go:788 +0x28a
go.k6.io/k6/js.(*ActiveVU).RunOnce(0xc000fd4640)
        go.k6.io/k6@v0.42.0/js/runner.go:733 +0x412
go.k6.io/k6/lib/executor.getIterationRunner.func1({0x252f608, 0xc002140960}, {0x2523f40?, 0xc000fd4640?})
        go.k6.io/k6@v0.42.0/lib/executor/helpers.go:124 +0x64
go.k6.io/k6/lib/executor.ConstantVUs.Run.func5({0x252a8f8, 0xc000ffce40})
        go.k6.io/k6@v0.42.0/lib/executor/constant_vus.go:193 +0x36f
created by go.k6.io/k6/lib/executor.ConstantVUs.Run
        go.k6.io/k6@v0.42.0/lib/executor/constant_vus.go:204 +0x90e

Goja stack:
native 

running (0m44.4s), 00/52 VUs, 488 complete and 52 interrupted iterations
get   ✗ [===========================>----------] 50 VUs  0m44.4s/1m0s
login ✗ [===========================>----------] 2 VUs   0m44.4s/1m0s
ERRO[0045] communicating with browser: websocket: close 1006 (abnormal closure): unexpected EOF  category=cdp elapsed="0 ms" goroutine=9255
ERRO[0045] process with PID 28716 unexpectedly ended: signal: killed  category=browser elapsed="2 ms" goroutine=9240

     ✓ Radix Navbar Company LOGO

     █ notificationServiceRequest

       ✗ Notification get endpoint status is 200
        ↳  0% — ✓ 0 / ✗ 485

     browser_dom_content_loaded.................: avg=1.97s    min=100µs   med=1.57s    max=7.21s    p(90)=4.16s    p(95)=5.47s   
     browser_first_contentful_paint.............: avg=3.17s    min=1.47s   med=2.78s    max=7.12s    p(90)=5.19s    p(95)=6.16s   
     browser_first_meaningful_paint.............: avg=1.8s     min=1.8s    med=1.8s     max=1.8s     p(90)=1.8s     p(95)=1.8s    
     browser_first_paint........................: avg=1.6s     min=21.09ms med=1.47s    max=7.12s    p(90)=3.4s     p(95)=5.26s   
     browser_loaded.............................: avg=3.57s    min=1.42ms  med=1.98ms   max=20.48s   p(90)=7.75s    p(95)=14.11s  
     checks.....................................: 0.61%   ✓ 3         ✗ 485 
     ✗ { myTag:notificationAPI }................: 0.00%   ✓ 0         ✗ 485 
     ✓ { myTag:notificationUI }.................: 100.00% ✓ 3         ✗ 0   
     data_received..............................: 163 MB  3.7 MB/s
     data_sent..................................: 1.3 MB  30 kB/s
     group_duration.............................: avg=2.55s    min=2.38s   med=2.49s    max=9.71s    p(90)=2.74s    p(95)=2.87s   
     http_req_blocked...........................: avg=13.95ms  min=0s      med=0s       max=527.74ms p(90)=1µs      p(95)=24µs    
     http_req_connecting........................: avg=5.31ms   min=0s      med=0s       max=302ms    p(90)=0s       p(95)=51.19ms 
   ✓ http_req_duration..........................: avg=253ms    min=12.45ms med=192.38ms max=5.24s    p(90)=493.77ms p(95)=534.81ms
       { expected_response:true }...............: avg=463.17ms min=350.2ms med=446.86ms max=1.02s    p(90)=534.56ms p(95)=608.91ms
     ✓ { group:::notificationServiceRequest }...: avg=270.71ms min=19.6ms  med=380.8ms  max=5.24s    p(90)=503.94ms p(95)=536.97ms
   ✗ http_req_failed............................: 47.60%  ✓ 486       ✗ 535 
     ✗ { group:::notificationServiceRequest }...: 47.60%  ✓ 486       ✗ 535 
     http_req_receiving.........................: avg=49.83ms  min=0s      med=84µs     max=2.76s    p(90)=142ms    p(95)=278.16ms
     http_req_sending...........................: avg=81.49µs  min=0s      med=57µs     max=8ms      p(90)=105µs    p(95)=140.25µs
     http_req_tls_handshaking...................: avg=9.4ms    min=0s      med=0s       max=449.18ms p(90)=0s       p(95)=39ms    
     http_req_waiting...........................: avg=263.37ms min=19.53ms med=374.92ms max=5.24s    p(90)=493.33ms p(95)=524.77ms
     http_reqs..................................: 1456    32.77243/s
     iteration_duration.........................: avg=2.68s    min=2.38s   med=2.49s    max=31.52s   p(90)=2.74s    p(95)=2.9s    
     iterations.................................: 489     11.006675/s
     vus........................................: 52      min=52      max=52
     vus_max....................................: 52      min=52      max=52

ERRO[0045] a panic occurred during JS execution: runtime error: invalid memory address or nil pointer dereference

**Comment by inancgumus** [comment]
It's no longer reproducible.
