### ISSUE TITLE
locator.dragTo(target[, options])

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#336]
This issue is blocked because neither the `Page` nor `Frame` types support `DragAndDrop`. Adding a locator does not make sense at this moment. We should first add support to `Page` and `Frame` (and `ElementHandle`), and then implement the locator side later. See: #368.

**Comment by andrewslotin** [comment]
Replaced by https://github.com/grafana/xk6-browser/issues/1118
