### ISSUE TITLE
k6 Cloud: missing HTTP-level metrics

### ISSUE THREAD

**Issue by tom-miseur** [grafana/xk6-browser#370]
Tests with metrics streamed to the k6 Cloud are not currently displaying HTTP-level metrics:

![image](https://user-images.githubusercontent.com/37644300/171954103-54723b22-327c-43fc-b72e-7ff25ece9213.png)

Group-level metrics are present though (bottom of screenshot).

**Comment by inancgumus** [comment]
Hi @tom-miseur, could you share your script and the exact steps you've taken for me to reproduce this issue?

What do you think about this? @grafana/k6-backend

**Comment by esquonk** [comment]
Made a fix for processing of incomplete metrics, hopefully this will fix the issue once released:
https://github.com/grafana/k6-backend/issues/254

**Comment by inancgumus** [comment]
Update: The latest fix didn’t seem to work.

**Comment by inancgumus** [comment]
Update: Marat will be looking into this issue today (he was busy finishing multi-db config for metrics databases).

**Comment by inancgumus** [comment]
Update: Requested to re-open the issue in the backend-side: https://github.com/grafana/k6-backend/issues/254#issuecomment-1160395246.

**Comment by inancgumus** [comment]
Update: Pawel asked the backend team to prioritize the feature.

**Comment by inancgumus** [comment]
Update: Marat has found the issue. The metrics submitted from xk6-browser don't have a name tag (and no `expected_response` tag, for that matter). I can correct that during ingest. And retroactively fix metrics (maybe). And, he'll put the fix for new test runs in staging today and it's going to production tomorrow
