### ISSUE TITLE
Browser should not override defaults with null values

### ISSUE THREAD

**Issue by GavinB-hpe** [grafana/xk6-browser#407]
If the executablePath is set to null, then chromium will not be found. My expectation would be that null should 
imply default behavior.

```
export default function() {
    const browser = launcher.launch('chromium', {
        executablePath: null,       // Override search for browser executable in favor of specified absolute path
    });
```

**Comment by GavinB-hpe** [comment]
Especially as the error message is wrong - it says browser executable not in $PATH or something similar.  And of course it is!

**Comment by ankur22** [comment]
Thanks for raising this @GavinB-hpe. I think we're going to go down the route of making the error message clearer (as well as the documentation) to ensure that the `null` for `executablePath` is a bad input value.
