### ISSUE TITLE
Force browser options in Cloud test runs

### ISSUE THREAD

**Issue by imiric** [grafana/xk6-browser#414]
In order to ensure users don't run into confusing issues when running xk6-browser tests in the Cloud, we should override certain [options passed to `BrowserType.Launch`](https://github.com/grafana/xk6-browser/blob/eb136726e37282fffad0c642062a04a6680a6adc/README.md?plain=1#L106-L115) and ultimately to the browser process.

For example:
- `headless` in the Cloud must currently be set to `true`, as we don't have the capability to run with a browser UI, and arguably don't need to.
- `executablePath` shouldn't be configurable in the Cloud.
- `devtools` should be ignored.

We should ensure that whatever these options are configured as, they are passed a fixed value in Cloud test runs.

## Suggested solution

We have to detect some way that we're running in the Cloud, maybe with an existing or additional env var(?). Consult with the k6 or Backend team about the best approach.

And then the change to override the options should be done around here:
https://github.com/grafana/xk6-browser/blob/eb136726e37282fffad0c642062a04a6680a6adc/chromium/browser_type.go#L208-L213

## Update

We can detect whether we're running in the cloud by checking the environment variable `K6_CLOUDRUN_INSTANCE_ID`. See [this page](https://k6.io/docs/cloud/creating-and-running-a-test/cloud-tests-from-the-cli/#cloud-environment-variables) for more details.

https://github.com/grafana/xk6-browser/issues/414#tasklist-block-ca1a6fa1-4189-43f1-8bb9-d1229b670ebe

**Comment by imiric** [comment]
I'm increasing the priority of this, since it's a blocker for even the initial public beta.

**Comment by inancgumus** [comment]
Hey @mdcruz, #627 should solve this problem. What do you think about adding it to the documentation?

We will ignore `headless`, `executablePath`, and `devtools` while running a test on the cloud.

**Comment by mdcruz** [comment]
> Hey @mdcruz, #627 should solve this problem.
> 
> We will ignore the `headless`, `executablePath`, and `devtools` options while running a test on the cloud. And we'll display a log message as the following:
> 
> ```
> // Let's say headless is set to false.
> WARN[0000] setting headless option is disallowed on cloud.
> ```
> 
> What do you think about adding it to the documentation?

This will require further analysis because the get started guide is specifically just for running xk6-browser locally (for now). There is also a section called [cloud docs](https://k6.io/docs/cloud/), so we need to decide if we want to add instructions on running xk6-browser in the cloud in this section instead.

**Comment by MattDodsonEnglish** [comment]
> There is also a section called [cloud docs](https://k6.io/docs/cloud/), so we need to decide if we want to add instructions on running xk6-browser in the cloud in this section instead.

Thanks for bringing this up. At first glance, I think it would be best to keep the cloud-specific details of xk6-browser with the wider xk6-browser docs. If there's something very different about xk6-browser and k6 Cloud, we could consider adding a page or section in the Cloud docs, but I'm guessing it'll just be some differences in parameters, as it seems in this case.

As precedent, the [handleSummary() docs](https://k6.io/docs/results-output/end-of-test/custom-summary/) have a note that says that this works only on local tests. And the `/using-k6` OSS pages  usually end with a little picture of the feature as visualized in the Cloud.
