### ISSUE TITLE
Intermittent test failures and flaky tests

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#427]
For a few months now we've noticed an increase in intermittent test failures (e.g. #421), as well very frequent flaky tests and CI failures (#272, #254). This has become a major issue for both users and internal devs working on the extension.

From initial work explored in #281 that aimed to fix #272, it became apparent that these issues stem from the racy nature of how we [process CDP events](https://github.com/grafana/xk6-browser/blob/6baeca02e7515dc5b39c05601078e27688ee0e88/common/connection.go#L279), [which can trigger one](https://github.com/grafana/xk6-browser/blob/6baeca02e7515dc5b39c05601078e27688ee0e88/common/network_manager.go#L368-L382) or [more internal events](https://github.com/grafana/xk6-browser/blob/6baeca02e7515dc5b39c05601078e27688ee0e88/common/frame_manager.go#L162). This is explained in detail in [this discussion](https://github.com/grafana/xk6-browser/discussions/142), along with a proposed architecture to address these issues.

An ancillary problem with the current architecture is that these event flows and race conditions are difficult to trace and understand, and since they're intermittent and difficult to test we're never sure if we're introducing more of them as we make changes.

## Example

To illustrate an example of a race condition that should be addressed, consider the following scenario from [`TestPageGoto`](https://github.com/grafana/xk6-browser/blob/6baeca02e7515dc5b39c05601078e27688ee0e88/tests/page_test.go#L147-L156) (failure example in [CI build #1123](https://github.com/grafana/xk6-browser/runs/7181619757)):

1. xk6-browser sends the `Page.navigate` CDP command:
    ```
    -> {"id":20,"sessionId":"75F7E22B7AD1085646FE46C053DD6729","method":"Page.navigate","params":{"url":"http://127.0.0.1:40721/static/empty.html","frameId":"AF0723A7356FB62639D7BA483EBF615E"}}
    ```
    Done here:
    https://github.com/grafana/xk6-browser/blob/6baeca02e7515dc5b39c05601078e27688ee0e88/common/frame_manager.go#L617

2. The browser responds with the `load` `Page.lifecycleEvent`:
    ```
    <- {"method":"Page.lifecycleEvent","params":{"frameId":"E0C85D008DBA499F54F24A284F032911","loaderId":"B16AD01C43E1F176E80ED03C4F35081E","name":"load","timestamp":564.999827},"sessionId":"8CC5472C3955F483AFA9B01CA9ED3B2C"}
    ```
    ... which we process _before_ we've had the chance to setup the waiter for it here:
https://github.com/grafana/xk6-browser/blob/6baeca02e7515dc5b39c05601078e27688ee0e88/common/helpers.go#L156-L169

    This leads to us missing the event, and waiting for a second `load` event which never arrives, ultimately timing out at the default 30s.

This is a very simple scenario, and other more complex ones are common as well. For example, the race condition between calling `ElementHandle.click()` and `Page.waitForNavigation()`, or calling `Page.waitForSelector()` while a hard navigation is in progress, which resets the `ExecutionContext`, so we end up evaluating the `injected.waitForSelector()` JS call with a stale `ExecutionContext`, causing the cryptic `Cannot find context with specified id (-32000)` error, etc.

## Proposed Solution

In the #142 discussion we mentioned [removing the internal event-based system in favor of an event-driven finite-state machine](https://github.com/grafana/xk6-browser/discussions/142#discussioncomment-2416943). This might be overkill and would introduce additional complexity, so we might want to look into simpler solutions by e.g. synchronizing CDP and internal event processing in such a way that waiters are setup before the CDP event is sent, ensuring we never have a chance to miss an incoming event. This solution was explored in #281, but we had other test issues with that approach and never merged it.

OTOH, targetted solutions like this would have to be done on a case-by-case basis, whereas a general removal of the internal event-based system and introduction of an FSM should work in all cases, so that might be preferable. Some investigation is needed to settle on the better approach.

Another solution (#428) that would improve things is exposing more async APIs. E.g. in the `click()`/`waitForNavigation()` example above, if both of these methods returned a `Promise`, we could document that the user must use `Promise.all()` to synchronize both calls, in order to setup `waitForNavigation()` before `click()` is called. You can see that [Playwright mentions this approach in their documentation](https://playwright.dev/docs/api/class-page#page-wait-for-navigation).

**Comment by inancgumus** [comment]
Feel free to edit the description, @imiric 👍

**Comment by inancgumus** [comment]
Yes, I was suggesting using Promises to do that 😌

> Hopefully, maybe we can do it using https://github.com/grafana/xk6-browser/issues/428. Like Puppeteer and Playwright, we can put the relevant actions into the same promise. That would hopefully remove the need for a frame-specific barrier.

And, as I explained in #142, +1 for major refactoring. Anyway, let's discuss the rest of the details in the architectural refactoring and async API meeting 🤝

**Comment by imiric** [comment]
@grafana/k6browserdev What should we do with this issue? The main race conditions mentioned in the description have now been fixed, and the major refactoring approach discussed above is not a high priority to address this, and has been downscoped from our initial plans.

We do still have intermittent test failures and flaky tests, but it's not clear what the "definition of Done" is for this particular issue.

So I vote to close this, and open new issues for specific flaky behavior. Or we could reuse this issue as a general one for all such behavior, but there's a lot of noise in the discussion above, and we'd need to change the description and add a TODO list, so we might as well open a new issue even in that case.

**Comment by mstoykov** [comment]
I also prefer to have issues per flaky test (or behaviour) as that way it could be discussed per case what hte solution can be

**Comment by ankur22** [comment]
> So I vote to close this, and open new issues for specific flaky behavior.

> I also prefer to have issues per flaky test (or behaviour) as that way it could be discussed per case what hte solution can be

Agreed with both of these 👍

**Comment by inancgumus** [comment]
IMO, we can close this one and give a reference to this from the new issues when needed.

**Comment by imiric** [comment]
OK, closing this, and let's open one issue per flaky behavior we find. Though maybe not immediately if it happens once in CI, but if it really becomes a problem.
