### ISSUE TITLE
Browser v2: Async APIs

### ISSUE THREAD

**Issue by sniku** [grafana/xk6-browser#428]
```[tasklist]
### Migrate to Async
```

```[tasklist]
### Nice to have
- [ ] grafana/jslib.k6.io#125
```

```[tasklist]
### Migration is complete - Document the changes
```

```[tasklist]
### Done Done
- [ ] #1362
- [ ] #1302
- [ ] #683
- [ ] #463
- [ ] #439
- [ ] #440
- [ ] #1251
- [ ] #583
- [ ] #1294
- [ ] #1295
- [ ] #1296
- [ ] #1303
- [ ] #1304
- [ ] #1305
- [ ] #1306
- [ ] #1307
- [ ] #1308
- [ ] #1309
- [ ] #1359
- [ ] #1321
- [ ] #1298
- [ ] grafana/k6-docs#1600
```

---

## What

This issue has been repurposed to initiate and follow the progress of migrating most of the browser APIs to async (promise based).

A recent example is this [issue](https://github.com/grafana/xk6-browser/issues/1251) where `touchscreen.tap` was migrated to async:

From:

```js
page.touchscreen.tap(...);
```

To:

```js
await page.touchscreen.tap(...);
```

## Why

1. Most browser APIs use some form of long-running IO operation (networking) to perform the requested action on the web browser against the website under test. We need to avoid blocking JavaScript's runtime event loop for such operations.
2. We're going to add more asynchronous event-based APIs (such as [page.on](https://github.com/grafana/xk6-browser/issues/1227)) that our current synchronous APIs would block.
3. To align with how developers expect to work with JavaScript APIs.
4. To have better compatibility with Playwright.

## How

We have detailed exactly which APIs will most likely need to be migrated across in the [comment](https://github.com/grafana/xk6-browser/issues/428#issuecomment-1964020837) within this issue. For most of the APIs we can take a look at the comment and migrate the APIs that are listed there. It's worth noting that it's still best to double check whether the API needs to be migrated especially ones which k6 browser implements but aren't provided by Playwright, for example `page.throttleCPU`.

### NOT Implemented In PW

If an API is not implemented in PW, then you should be able to answer yes to one of the questions in the list below to determine whether it should be async or not, for example `browser.context` is not in PW, and it doesn't do any IO or long running tasks, therefore it can stay as a synchronous API.

1. Does the API perform a network call or other IO operations, this includes a CDP request to Chrome?
2. Does the API perform long running task?

### Implemented in PW

Is the API in the list in this [comment](https://github.com/grafana/xk6-browser/issues/428#issuecomment-1964020837) and is implemented in PW?

If the answer is yes, then it can be migrated to async.

### Goja, docs and type defs

Initially we're only interested in moving the API to async, and not worrying about goja, doc and type definitions updates. Doc and type definition updates will be deferred to after the implementation work and before the release. We're hoping that the goja refactoring/abstraction work can also be shifted to a later point, but we may find that some APIs will also need goja to be refactored out of them to prevent panics and race conditions.

**Comment by ankur22** [comment]
I believe this is an up to date list of APIs that we should move over to be asynchronous (i.e. wrap the return in a `Promise`). The list was created by comparing the return types between [Playwright's](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/types/types.d.ts) and [k6's](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/k6/experimental/browser.d.ts) type definitions files.:

| Class | Method | Current k6 Return |
| ---- | ---- | ---- |
| Browser | closeContext | void |
| Browser | context | BrowserContext |
| Browser | newContext | BrowserContext |
| Browser | newPage | Page |
| BrowserContext | addCookies | void |
| BrowserContext | browser | Browser |
| BrowserContext | clearCookies | void |
| BrowserContext | clearPermissions | void |
| BrowserContext | close | void |
| BrowserContext | cookies | Cookie[] |
| BrowserContext | grantPermissions | void |
| BrowserContext | newPage | Page |
| BrowserContext | setGeolocation | void |
| BrowserContext | setOffline | void |
| ElementHandle | $ | ElementHandle\|null |
| ElementHandle | $$ | ElementHandle[] |
| ElementHandle | boundingBox | Rect |
| ElementHandle | contentFrame | Frame |
| ElementHandle | fill | void |
| ElementHandle | focus | void |
| ElementHandle | getAttribute | string\|null |
| ElementHandle | hover | void |
| ElementHandle | innerHTML | string |
| ElementHandle | innerText | string |
| ElementHandle | inputValue | string |
| ElementHandle | isChecked | boolean |
| ElementHandle | isDisabled | boolean |
| ElementHandle | isEditable | boolean |
| ElementHandle | isEnabled | boolean |
| ElementHandle | isHidden | boolean |
| ElementHandle | isVisible | boolean |
| ElementHandle | ownerFrame | Frame |
| ElementHandle | press | void |
| ElementHandle | screenshot | ArrayBuffer |
| ElementHandle | scrollIntoViewIfNeeded | void |
| ElementHandle | selectOption | string[] |
| ElementHandle | selectText | void |
| ElementHandle | tap | void |
| ElementHandle | textContent | string |
| ElementHandle | type | void |
| ElementHandle | uncheck | void |
| ElementHandle | waitForElementState | void |
| ElementHandle | waitForSelector | void |
| Frame | $ | ElementHandle\|null |
| Frame | $$ | ElementHandle[] |
| Frame | check | void |
| Frame | content | string |
| Frame | dblclick | void |
| Frame | dispatchEvent | void |
| Frame | evaluate<R, Arg> | R |
| Frame | evaluateHandle<R, Arg> | JSHandle<R> |
| Frame | fill | void |
| Frame | focus | void |
| Frame | frameElement | ElementHandle |
| Frame | getAttribute | string |
| Frame | hover | void |
| Frame | innerHTML | string |
| Frame | innerText | string |
| Frame | inputValue | string |
| Frame | isChecked | boolean |
| Frame | isDisabled | boolean |
| Frame | isEditable | boolean |
| Frame | isEnabled | boolean |
| Frame | isHidden | boolean |
| Frame | isVisible | boolean |
| Frame | press | void |
| Frame | selectOption | string[] |
| Frame | setContent | void |
| Frame | tap | void |
| Frame | textContent | string |
| Frame | title | string |
| Frame | type | void |
| Frame | uncheck | void |
| Frame | waitForLoadState | void |
| Frame | waitForSelector | ElementHandle |
| Frame | waitForTimeout | void |
| JSHandle | asElement | ElementHandle\|null |
| JSHandle | dispose | void |
| JSHandle | evaluate<R, Arg> | R |
| JSHandle | evaluateHandle<R, Arg> | JSHandle<R> |
| JSHandle | getProperties | Map<string,JSHandle> |
| JSHandle | jsonValue | any |
| Keyboard | down | void |
| Keyboard | insertText | void |
| Keyboard | press | void |
| Keyboard | type | void |
| Keyboard | up | void |
| Locator | check | void |
| Locator | clear | void |
| Locator | dblclick | void |
| Locator | dispatchEvent | void |
| Locator | fill | void |
| Locator | focus | void |
| Locator | getAttribute | string\|null |
| Locator | hover | void |
| Locator | innerHTML | string |
| Locator | innerText | string |
| Locator | inputValue | string |
| Locator | isChecked | boolean |
| Locator | isDisabled | boolean |
| Locator | isEditable | boolean |
| Locator | isEnabled | boolean |
| Locator | isHidden | boolean |
| Locator | isVisible | boolean |
| Locator | press | void |
| Locator | selectOption | string[] |
| Locator | tap | void |
| Locator | textContent | string |
| Locator | type | void |
| Locator | uncheck | void |
| Locator | waitFor | void |
| Mouse | click | void |
| Mouse | dblclick | void |
| Mouse | down | void |
| Mouse | move | void |
| Mouse | up | void |
| Page | $ | ElementHandle |
| Page | $$ | ElementHandle[] |
| Page | bringToFront | void |
| Page | check | void |
| Page | close | void |
| Page | content | string |
| Page | dblclick | void |
| Page | dispatchEvent | void |
| Page | emulateMedia | void |
| Page | emulateVisionDeficiency | void |
| Page | evaluate<R, Arg> | R |
| Page | evaluateHandle<R, Arg> | JSHandle<R> |
| Page | fill | void |
| Page | focus | void |
| Page | getAttribute | null\|string |
| Page | hover | void |
| Page | innerHTML | string |
| Page | innerText | string |
| Page | inputValue | string |
| Page | isChecked | boolean |
| Page | isDisabled | boolean |
| Page | isEditable | boolean |
| Page | isEnabled | boolean |
| Page | isHidden | boolean |
| Page | isVisible | boolean |
| Page | on | void |
| Page | opener | Page\|null |
| Page | press | void |
| Page | reload | null\|Response |
| Page | screenshot | ArrayBuffer |
| Page | selectOption | string[] |
| Page | setContent | void |
| Page | setExtraHTTPHeaders | void |
| Page | setViewportSize | void |
| Page | tap | void |
| Page | textContent | string |
| Page | throttleCPU | void |
| Page | throttleNetwork | void |
| Page | title | string |
| Page | type | void |
| Page | uncheck | void |
| Page | viewportSize | {width:number;height:number;} |
| Page | waitForLoadState | void |
| Page | waitForSelector | ElementHandle |
| Page | waitForTimeout | void |
| Request | allHeaders | Record<string,string> |
| Request | headerValue | string\|null |
| Request | headersArray | Array<{name:string;value:string}> |
| Request | postData | string |
| Request | resourceType | ResourceType |
| Request | response | Response\|null |
| Request | size | {body:number;headers:number} |
| Request | timing | ResourceTiming |
| Response | allHeaders | Record<string,string> |
| Response | body | ArrayBuffer |
| Response | headerValue | string\|null |
| Response | headerValues | string[] |
| Response | headersArray | Array<{name:string;value:string}> |
| Response | json | any |
| Response | securityDetails | SecurityDetailsObject\|null |
| Response | serverAddr | {ipAddress:string;port:number}\|null |
| Response | size | {body:number;headers:number} |
| Touchscreen | tap | void |

**Comment by ankur22** [comment]
It's worth noting that the browser module already has APIs (as of `v0.51.0`) that are already async:

* `browserContext.waitForevent`
* `elementHandle.click`
* `elementHandle.tap`
* `frame.click`
* `frame.goto`
* `frame.tap`
* `frame.waitForFunction`
* `frame.waitForNavigation`
* `locator.click`
* `locator.tap`
* `page.click`
* `page.goto`
* `page.tap`
* `page.waitForFunction`
* `page.waitForNavigation`

Even though we have these, the changes we are making will still affect all users and their scripts since APIs such as `browser.newPage` are required for all browser tests.

**Comment by ankur22** [comment]
Showcasing what to to expect when migrating your sync script to async with the `fillform.js` example:

NOTE: The changes required to work with `check`. Just like `group`, `check` doesn't work with async APIs.



![Image](https://github.com/grafana/xk6-browser/assets/1112428/63b400fe-d481-4b83-8853-a2af3a323798)
