### ISSUE TITLE
Create docs for ElementHandle class

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#448]
Create the documentation for the `ElementHandle` class as it is today (`v0.4.0`). This will be based on and following on from the work that was done in the following branches and PRs:

- Open Branches:
    - https://github.com/grafana/k6-docs/commits/xk6-browser-new-format
    - https://github.com/grafana/k6-docs/commits/docs/582-xk6-browser

- PRs:
    - https://github.com/grafana/k6-docs/pull/642
    - https://github.com/grafana/k6-docs/pull/508

**Comment by mdcruz** [comment]
@ankur22 @inancgumus Do we still need this issue? If so, I will add it to the [k6 Eng content board](https://github.com/orgs/grafana/projects/342/views/1?filterQuery=project%3A%22browser%2Fdisruptor%2Foperator%22)

**Comment by inancgumus** [comment]
IIRC, I think we do not since we already updated the `ElementHandle`. @ankur22?

**Comment by ankur22** [comment]
We've not updated the `ElementHandle` docs, i didn't get a chance to update them when i did the last large doc update. Happy for you to take it on @mdcruz

**Comment by andrewslotin** [comment]
Done
