### ISSUE TITLE
`args` option on `Launch` doesn't seem to append to the args when launching the browser

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#461]
Tested against: https://github.com/grafana/xk6-browser/commit/dbede120c63df43995813a847a25b0e66e289592

I was testing the `Launch` function with the following script as I was testing the `args` option:

```javascript
import { sleep } from 'k6';
import launcher from 'k6/x/browser';

export default function () {
  const browser = launcher.launch('chromium', {
    args: ['--show-property-changed-rects'],
    headless: false,
  });
  const context = browser.newContext();
  const page = context.newPage();
  const res = page.goto('https://maps.google.com');

  sleep(10);
  browser.close();
}
```

I was expecting coloured boxes to appear on screen as I hovered the mouse on the page like so:

<img width="533" alt="Screenshot 2022-07-15 at 14 13 32 (2)" src="https://user-images.githubusercontent.com/1112428/179230515-33c3dcd1-b95b-4b09-b8d4-62dfb30a43a3.png">

But this didn't happen and no boxes displayed anywhere.

**Comment by inancgumus** [comment]
This feature works. The argument should be without dash-dash as follows:

```js
const browser = launcher.launch('chromium', {
  args: ['show-property-changed-rects'],
  headless: false,
});
```

**Comment by inancgumus** [comment]
We should carefully document it! :-)
