### ISSUE TITLE
Support transparently selecting elements under a shadow DOM

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#475]
Tested against: https://github.com/grafana/xk6-browser/commit/dbede120c63df43995813a847a25b0e66e289592

When trying to create a script for an example to go on the documentation page, I found that the `checkbox` wasn't being found and it would eventually timeout. The script I ran using `k6-browser` was:

```javascript
import { sleep } from 'k6';
import launcher from 'k6/x/browser';

export default function () {
  const browser = launcher.launch('chromium', {
    headless: false,
  });
  const context = browser.newContext();
  const page = context.newPage();
  page.goto("https://interactive-examples.mdn.mozilla.net/pages/tabbed/input-checkbox.html");
  const checkbox = page.locator('#horns');
  checkbox.check();

  sleep(5);
  browser.close();
}
```

I tested the same scenario in PW using the following and it was able to correctly select the checkbox:

```javascript
// @ts-check
const { test, chromium } = require('@playwright/test');

test.describe('Editing', () => {
  test('Type login creds', async () => {
    const browser = await chromium.launch({ headless: false });
    const ctx = await browser.newContext();
    const page = await ctx.newPage();
    await page.goto("https://interactive-examples.mdn.mozilla.net/pages/tabbed/input-checkbox.html");
    const l = page.locator('#horns');
    l.check();

    await new Promise(resolve => setTimeout(resolve, 5000));

    await browser.close();
  });
});
```

**Comment by imiric** [comment]
This seems like a more general problem with selecting elements under a shadow DOM.

If you notice, `input#horns` is under a `#shadow-root` element. In DevTools you can't select it with `$('#horns')` either, but have to do something like `$('shadow-output').shadowRoot.querySelector('#horns')`. It's likely that Playwright supports this lookup transparently in some way, and we'd have to look into it. So I think this is more of a missing feature than a bug.
