### ISSUE TITLE
Error deleting temporary directory

### ISSUE THREAD

**Issue by imiric** [grafana/xk6-browser#484]
On v0.4.0 and possibly current `main` (00960bd), we've received reports that sometimes the temporary directory used for browser storage is not deleted, or not entirely deleted, due to some permission issues, on Windows and macOS.

Error on Windows (see [forum post](https://community.k6.io/t/browsermetrics-access-denied-error/4384)):

```
remove C:\Users\SHRI~1\AppData\Local\Temp\xk6-browser-data-1157189391\BrowserMetrics\BrowserMetrics-62EDCCCB-1870.pma: Access is denied. category="BrowserType:Launch" elapsed="78 ms" goroutine=58
```

Error on macOS (see [this comment](https://github.com/grafana/xk6-browser/issues/403#issuecomment-1167511842)) and Linux (seen on Cloud):

```
ERRO[0059] unlinkat /tmp/xk6-browser-data-3665988004: directory not empty category="Browser:Close" elapsed="0 ms" goroutine=83
```

It's likely that we're trying to remove the directory while the browser process is still running.

This is not related to #403 since the issue is not not calling the cleaning procedure, but a race between stopping the browser process and calling the cleaning procedure.

**Comment by imiric** [comment]
This might have also been fixed by #535, since we now ensure to call `dataDir.Cleanup()` after the process exits cleanly. I haven't noticed it in Cloud test runs at least. Has anyone seen this recently?

Let's leave this open for a couple of more weeks, and we can close it if we don't see it again.

**Comment by imiric** [comment]
I haven't seen this recently, so closing.

**Comment by inancgumus** [comment]
I saw this yesterday :( If the directory is not empty before launching the xk6-browser, it fails. It worked after manually erasing the directory.

**Comment by imiric** [comment]
Are you using a custom `user-data-dir`?

This issue was about the error happening during regular execution, not the scenario you're describing. It's probably a good thing that it fails in that case, and we don't try deleting an already existing directory.

**Comment by inancgumus** [comment]
No, I wasn't using `user-data-dir`. It was happening when there are directories in the temporary directory.
