### ISSUE TITLE
Implement `BrowserContext.addCookies(cookies)`

### ISSUE THREAD

**Issue by robingustafsson** [grafana/xk6-browser#5]
Add support for `BrowserContext.addCookies(cookies)`, allowing users to add default cookies to all pages created in browser context.

**Relevant links**:
- Playwright docs: https://playwright.dev/docs/api/class-browsercontext#browsercontextaddcookiescookies
- xk6-browser code to start: https://github.com/grafana/xk6-browser/blob/main/common/browser_context.go#L75
- Playwright code: https://github.com/microsoft/playwright/blob/master/src/server/chromium/crBrowser.ts#L382
- Playwright tests: https://github.com/microsoft/playwright/blob/master/tests/browsercontext-add-cookies.spec.ts

**Comment by zucchinho** [comment]
i need this feature for some load tests i'm writing, i'm happy to pick take a stab at this

**Comment by ankur22** [comment]
Hi @zucchinho,

Thanks for offering your time to help us implement this method. We'd be happy for you take a stab at it. We've just added the [contributing guidelines](https://github.com/grafana/xk6-browser/blob/main/CONTRIBUTING.md), take a look and good luck 🙂 👍
