### ISSUE TITLE
Temporary execution pauses in the Cloud 

### ISSUE THREAD

**Issue by imiric** [grafana/xk6-browser#502]
In the most recent Cloud deployment (7722b29), running a 1VU/1h test of [a slightly modified version of `fillform.js`](https://github.com/grafana/xk6-browser/blob/9622c4c2640014536d7814f5ff7598b16dd7ca39/examples/fillform.js) shows frequent but seemingly random execution pauses, where CPU usage and Request Rate drop to effectively 0 for a few seconds:

![2022-08-16-210539_1920x1080_scrot](https://user-images.githubusercontent.com/1009277/184963176-dabb86fd-16b8-43fc-b32c-fb70460909c5.png)

See test runs 140715 on staging, and 1458715 on production.

This is similar to #496, except that things recover after a few seconds, and there's seemingly no interruption in metric emission:
![2022-08-16-211745_1920x1080_scrot](https://user-images.githubusercontent.com/1009277/184964534-18a02d4a-9a2c-4072-a0fd-0d142af62749.png)

The logs don't show much besides the usual `communicating with browser: websocket: close 1006 (abnormal closure): unexpected EOF` error probably at the end of each iteration.

Could this be some metric emission related pause? Once we enable `pprof` we should be able to have a better understanding of what's happening during each pause. cc: @ankur22

**Comment by ankur22** [comment]
Is it possible to test this locally? I would've thought it was easier to find locally since it seems to rear its ugly head with lower latencies.

I wonder if it's possible to record all the events that occur during a "good" run where there are no pauses, and compare it to the list of events that occur during the same test but when a pause occurs -- this might help us to determine whether it's out of order events again.

**Comment by imiric** [comment]
@ankur22 Sorry about the delay.

> Is it possible to test this locally?

I have seen some of the timeouts mentioned above _very_ rarely on my local machine, but not this behavior where it happens frequently. I haven't even been able to reproduce this in a standalone EC2 instance, and it only happens when actually running a Cloud test. So it's very cumbersome to troubleshoot, unfortunately. :disappointed: 

Good idea about recording events and making a comparison. I did something similar by manually comparing debug trace logs, but it's difficult to spot the causes, since it might not be related to receiving CDP events, but the timing of how we process them. So you end up comparing the times of log events, which is :exploding_head:.

On a sidenote, our logs should definitely be more precise than the current second precision to help with troubleshooting. I tried to increase the precision a few months back, but wasn't able to for some reason. :confused:

**Comment by imiric** [comment]
Another data point: I ran a test on an `i3.xlarge` instance yesterday (4 vCPU, 30.5GB RAM), which is a storage optimized instance with better IOPS performance.

See test run 141349:
![2022-10-07-123128_1539x774_scrot](https://user-images.githubusercontent.com/1009277/194535355-ca435655-fa86-427a-ad2f-996d24a47205.png)

So we see much less interruptions than on the traditional `m5.large` instance.

But the surprising thing is that I didn't notice the system struggling with disk I/O. `top` showed all cores mostly at `0.0 wa`, and `iotop` showed a few KB/s of utilization by relevant processes at all times.

So I would discard disk I/O being a bottleneck in these cases. Maybe the bump in vCPUs (2 vs 4) had more to do with the better performance than anything else.

**Comment by imiric** [comment]
After #555, we no longer see this issue in the Cloud :tada: So I'm closing this.
