### ISSUE TITLE
[Question] Browser metrices from k6

### ISSUE THREAD

**Issue by jithinjosejacob** [grafana/xk6-browser#513]
I am doing a load test for a specific page in my app using xk6 browser. I login to app wait for navigation, navigate to the specific page from dashboard. Wait for load, perform filtering. Finally I get some stats regarding browser load time. Is the browser load times correspondening to my last action or is it average of all load times

**Comment by imiric** [comment]
Hi there, I'll answer your question, but next time please use the [community forum](https://community.k6.io/c/xk6-browser/14) for questions. See our [Support document](https://github.com/grafana/xk6-browser/blob/main/SUPPORT.md).

The end-of-test summary shows aggregated metric stats for all pages loaded during the test. If you want to see individual metric samples, you can export them to an [output](https://k6.io/docs/getting-started/results-output/), or configure a [threshold](https://k6.io/docs/using-k6/thresholds/) per group or URL (note that thresholds per URL will be deprecated in k6 soon).
