### ISSUE TITLE
[Question] custom threshold configuration

### ISSUE THREAD

**Issue by jithintill** [grafana/xk6-browser#514]
While using 

  thresholds :{
    'browser_dom_content_loaded{url:https://www.google.com}' : ['p(90) < 1000'],
  }

custom threshold value is coming up as 0 with below warning

`WARN[0000] Thresholds like 'browser_dom_content_loaded{url:https://www.google.com}', based on the high-cardinality 'url' metric tag, are deprecated and will not be supported in future k6 releases. To prevent breaking changes and reduce bugs, use the 'name' metric tag instead, seeURL grouping (https://k6.io/docs/using-k6/http-requests/#url-grouping) for more information.  component=metrics-engine`

Can you please let me know the change to be made to make custom thresholds work

**Comment by imiric** [comment]
Hi, the reporting of 0s was a bug that was recently fixed on `main`, and the fix will be part of the upcoming v0.5.0 release (scheduled for next week). If you don't want to wait, you can build a binary yourself with `xk6 build --with github.com/grafana/xk6-browser@main`.

The deprecation warning is from k6, which won't be supporting thresholds on the `url` metric tag soon. The workaround would be to assign a custom `name` tag to metrics produced by `page.goto()`, but this is not support in xk6-browser yet (see #504).

In the meantime, you could wrap your `page.goto()` calls in a [k6 group](https://k6.io/docs/using-k6/tags-and-groups/#groups), and define the threshold on the group. E.g. `'browser_dom_content_loaded{group:::google}': ['p(90)<1000]`.

Please use the [community forum](https://community.k6.io/c/xk6-browser/14) for questions next time, and see our [Support document](https://github.com/grafana/xk6-browser/blob/main/SUPPORT.md).
