### ISSUE TITLE
The "complex" test fails on the very first step (`page.goto`)

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#542]
Commit tested against: 8b52a028840dbaa5ae61937766d473fcde9fca10 (pre-v0.6.0).
Test script: "[complex](https://github.com/grafana/xk6-browser-tests/blob/main/complex/vistaprint.js)" test.

The "complex" test does not work against the version of xk6-browser mentioned above. It navigates to the site, but seems to fail to get passed the `waitUntil: 'networkidle'` stage of the `page.goto` action.

In a randomly chosen tagged version of xk6-browser (`v0.4.0`) it is able to consistently get through most of the "complex" test, so well passed the `page.goto` initial step.

**Comment by inancgumus** [comment]
There is regression somewhere, and `git bisect` can help even though the complex test script is somewhat flaky. Weirdly, we cannot even pass the `page.goto` stage with the script. I vote to make this a high priority after dealing with the current high-priority issues.

**Comment by mstoykov** [comment]
removing the `debug: false` fixed it for me

**Comment by mstoykov** [comment]
> removing the debug: false fixed it for me

This is no longer true with the latest version - I first hit what I fixed in #579 and then I get
```
go.k6.io/k6/js/common.Throw(0x1394a00?, {0x18b3ca0?, 0xc0012c0120?})
        go.k6.io/k6@v0.40.1-0.20221004153024-912b2790958d/js/common/util.go:20 +0x55
github.com/grafana/xk6-browser/k6ext.Panic({0x18c2b68, 0xc002384e40}, {0x1600224, 0x27}, {0xc003491df8, 0x2, 0x2})
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/k6ext/panic.go:51 +0x2d7
github.com/grafana/xk6-browser/common.(*FrameSession).onFrameNavigated(0xc001973c30, 0xc000af66c0, 0x20?)
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/frame_session.go:650 +0x2e9
github.com/grafana/xk6-browser/common.(*FrameSession).initEvents.func1()
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/frame_session.go:257 +0x694
created by github.com/grafana/xk6-browser/common.(*FrameSession).initEvents
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/frame_session.go:228 +0x1ab
```

Which seems like a case where we should log or return an error, but instead we panic. But no obvious logical error as in #579

**Comment by ankur22** [comment]
Interesting! I didn't come across this when I was running this locally. Instead I was facing the issue where `waitUntil: 'networkidle'` wasn't being handled correctly. The reason for that is the event fires (lifecycle event with `networkIdle`) before the `FrameSession` registers to the event loop. I'm currently looking to fix it in https://github.com/grafana/xk6-browser/pull/578.

**Comment by inancgumus** [comment]
It is not failing on the very first step :yay:
