### ISSUE TITLE
Document the default arguments when launching browsers

### ISSUE THREAD

**Issue by mstoykov** [grafana/xk6-browser#550]
As part of adding support for [ignoreDefaultArgs](https://github.com/grafana/xk6-browser/pull/547) it was raised that it will be beneficial for users to know which flags they can disable with it. 

Currently relevant code can be found [here](https://github.com/grafana/xk6-browser/blob/db80f94ff219bb1330f433d73dce15708f6a7451/chromium/browser_type.go#L270-L321)

**Comment by inancgumus** [comment]
@mdcruz WDYT about this?

**Comment by mdcruz** [comment]
@inancgumus I can see the benefits of it definitely. We've also had questions during k6 office hours regarding default option for headless so having the default arguments documented somewhere in our docs would be useful.
