### ISSUE TITLE
Update xk6-browser documentation

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#632]
`page.goto` is now async, and we now need to update the docs to to reflect that change.

All examples have already been updated.
I believe the readme is also up to date with the latest change.

https://github.com/grafana/xk6-browser/issues/632#tasklist-block-b215f32e-6893-47ac-bfe5-6ad2a5423a31

**Comment by mdcruz** [comment]
Also included as part of https://github.com/grafana/k6-docs/pull/828

**Comment by inancgumus** [comment]
The video in the README is also outdated with the new `page.Goto`.

**Comment by mdcruz** [comment]
https://user-images.githubusercontent.com/10811379/200350050-f346931f-6402-487e-bf4d-eff808ac2190.mp4 created

**Comment by inancgumus** [comment]
Thanks, @mdcruz 🙇  It looks great.

**Comment by inancgumus** [comment]
@mdcruz, I've assigned this issue to you since you've fixed the problems!

I've noticed another issue: _Update the examples in the README (or completely remove them)_. Our examples in the README don't use the async `page.Goto` :-( WDYT about removing those examples completely from there any redirect people to the documentation?

**Comment by mdcruz** [comment]
> @mdcruz, I've assigned this issue to you since you've fixed the problems!
> 
> I've noticed another issue: _Update the examples in the README (or completely remove them)_. Our examples in the README don't use the async `page.Goto` :-( WDYT about removing those examples completely from there any redirect people to the documentation?

Yup, I think we should remove them and redirect the users to our official docs instead like you said. The plan is to follow the README approach for [Loki](https://github.com/grafana/loki)/[Tempo](https://github.com/grafana/tempo)/[Mimir](https://github.com/grafana/mimir). I'll work on this :)
