### ISSUE TITLE
Deadlock: TestPageWaitForFunction

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#637]
There's a deadlock when running `TestPageWaitForFunction` when ran with the following command:

> ```go
> go test ./tests -run='TestPageWaitForFunction' -count=100 -timeout=10s
> ```

_Originally posted by @inancgumus in https://github.com/grafana/xk6-browser/pull/636#pullrequestreview-1170396996_

This was tested on macOS. The logs for the test run with the deadlock has been attached.
      
[output1.log](https://github.com/grafana/xk6-browser/files/9952047/output1.log)

**Comment by inancgumus** [comment]
I fear this is a more overarching problem than `TestPageWaitForFunction`. For example:


```bash
go test ./tests -run='TestWaitForFrameNavigation' -count=100 -timeout=10s
```

Fails with a timeout as well.

**Comment by ankur22** [comment]
@inancgumus I don't think this test has a deadlock. This command is running 100 tests, one after the other and the timeout is set to 10 seconds. However this test takes 3-4secs when count is 1, therefore it will take 300-400 seconds to complete 100 tests.

```cmd
go test ./tests -run='TestPageWaitForFunction' -count=100 -timeout=10s
```

When i leave the timeout at the default value of 10 minutes, the test passes:

```cmd
go test ./tests -run='TestPageWaitForFunction' -count=100
```

**Comment by inancgumus** [comment]
Nice, let's close it then.
