### ISSUE TITLE
Restrict options with a new env var

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#640]
In #627, we implemented forcing some of the browser launch options when running in specific environments. However, it turned out that the variable wasn't an environment variable. Instead, we should define a new env var that can restrict options on the Cloud, such as `K6_BROWSER_RESTRICTED`.

More discussion is here: https://github.com/grafana/k6-cloud-agent/issues/192

**Comment by ankur22** [comment]
We're closing this as we have agreed that the environment itself will help restrict options for us.
