### ISSUE TITLE
Prepare for k6 private beta planning

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#651]
In preparation for the public beta, the k6 OSS Core team would like to get a better idea of where the project is. They're like a better understanding of:

- [ ] After the merge, do we stop making xk6-browser releases?
    - Inanc: I think k6 can `go mod` download from our latest tagged version. So we might keep making releases. Maybe without Windows/OSX/Linux executables, though.
    - Ankur: I think it should be the same as the other experimental extensions, and it looks like they don't make any more releases after the merge. I don't see any benefit of a release after the merge. We should put all our efforts into ensuring the merged version works and not worry about the xk6-browser release. This will also avoid any confusions where a user maybe trying to work with a xk6-browser release instead of the merged release -- although it shouldn't make a difference which one is used.
- [x] how it works; (Ankur: https://github.com/grafana/k6-internal-docs/pull/251)
- [x] what known security issues exist and how we plan to tackle them (OSS & Cloud);
    - Ankur: Deleting the temp dir is the only one i'm aware of. Inanc: How is this could be a security issue?
    - Ankur: Could someone exec malicious code via the browser (either in it or by downloading a binary)? Inanc: That's a possibility as I mentioned in the last sync agenda.
- [x] xk6-browser binary size is smaller than k6, why?
    - Ankur: This is because of the -ldflags='-w -s' that is used during the building of the `xk6-browser` binary.
        - `-s` will omit the symbol table and debug information.
        - `-w` will omit the DWARF symbol table.
    - Running `go build -ldflags='-w -s' -o k6 ` will build a 31MB binary file of k6 (latest release `v0.41.0`), and when zipped it is 10MB.

This initial meeting will likely bring out further questions we need to address.

**Comment by inancgumus** [comment]
[This CI failure](https://github.com/grafana/xk6-browser/actions/runs/3648103242/jobs/6161129576) shows us another problem: We can't keep compatible with k6-core before they release a new version. Our CI would fail like this if we try to act quickly and stay compatible with them unless they release a new version.

**Comment by inancgumus** [comment]
[This CI failure](https://github.com/grafana/xk6-browser/actions/runs/3648103242/jobs/6161129576) shows us another problem: We can't keep compatible with k6-core before k6-core releases a new version. Our CI will fail like this if we try to act quickly and stay compatible with k6-core unless k6-core releases the next version.

**Comment by ankur22** [comment]
> [This CI failure](https://github.com/grafana/xk6-browser/actions/runs/3648103242/jobs/6161129576) shows us another problem: We can't keep compatible with k6-core before k6-core releases a new version.

Yeah, this is related to https://github.com/grafana/xk6-browser/issues/659, which will need to be a priority in the next cycle.

**Comment by inancgumus** [comment]
@grafana/k6-browser @andrewslotin

Should we close this issue now since we have almost merged with the k6-core and we have an upcoming proposal for the cloud part? Then maybe refer to this issue in the proposal 🤔
