### ISSUE TITLE
Rename import path to k6/experimental/browser

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#668]
After the merge, k6 core will register the extension as `k6/experimental/browser`. However, we currently use it as [`k6/x/browser`](https://github.com/grafana/xk6-browser/blob/fbcd5a40e7b1a97078d1a226bc0ab96b188b251d/examples/fillform.js#L2)—since we register it as [this](https://github.com/grafana/xk6-browser/blob/fbcd5a40e7b1a97078d1a226bc0ab96b188b251d/main.go#L75). This means new scripts will import `k6/experimental/browser` to use the k6 browser features in JavaScript tests.

I believe we better update [the k6-browser registration code](https://github.com/grafana/xk6-browser/blob/fbcd5a40e7b1a97078d1a226bc0ab96b188b251d/main.go#L75) to the new import path (`k6/experimental/browser`); so we use the same new import paths both in k6-core and k6-browser.

Let's say we keep `k6/x/browser` in k6-browser registration and use `k6/experimental/browser` only in k6-core. Suppose someone wants to look into the examples folder. They'll be surprised and see `k6/x` imported instead of `k6/experimental/browser`. We, as developers, can also get confused and need to deal with different import paths while developing and testing.

## Problem

However, currently, we can't change the import path on our [side](https://github.com/grafana/xk6-browser/blob/fbcd5a40e7b1a97078d1a226bc0ab96b188b251d/main.go#L75). To see why let's run the following in the xk6-browser local repo after updating the import path to `k6/experimental/browser`:

```bash
$ xk6 run examples/launch_naked.js
...
[examples/launch_naked.js](panic: external module names must be prefixed with 'k6/x/', tried to register: k6/experimental/browser)
...
```

As you can see, xk6 can't run a module [that does not start with the `k6/x` prefix](https://pkg.go.dev/go.k6.io/k6/js/modules#Register). That's a problem because we want to use the new import path.

Before opening up an issue in xk6, I want to hear your thoughts.

**Comment by inancgumus** [comment]
@andrewslotin @grafana/k6-devs WDYT about this? 👀

**Comment by ankur22** [comment]
Btw, The panic occurs [here](https://github.com/grafana/k6/blob/5b70e70b657750234651a337c1b736c177926855/js/modules/modules.go#L27).

I had a look at the three other experimental modules, and they all register under `k6/x` (websocket example [here](https://github.com/grafana/xk6-websockets/blob/main/register.go)).

I'd prefer to have it consistent, so placed under `k6/experimental`. At the moment I can only think of two possibilities:
1. Ask the `k6` team if there is a workaround for this.
2. Ensure that we always only use `k6/experimental` in our docs and examples and redirect users to work with the release binary that is in the `k6` repo. If anyone is building it themselves we would need to put a big warning in the readme, as well as logging something to make it clear when the module is registered under `k6/x`.

My preference is option 1.

**Comment by inancgumus** [comment]
Mihail:

For all other experimental extensions, we have:

1. made them usable from within k6 as `k6/experimental/something`
2. let users build it with xk6 at which point they are accessible as `k6/x/something` as well

This does not require changing anything, and in the end, both `k6/experimental/something` and `k6/x/something` import the same code(*) due to how Go modules work.

So it seems to me like you should keep registering `k6/x/browser` going forward. Users are just way more likely that will always use `k6/experimental/browser`.

As the caching for the exports of a module is based on its specifier and the specifier is different - if somebody imports it with `x` and `experimental`, they will get two different exports objects - this is ... a corner case that likely should be fixed internally but doesn't seem to have real consequences for any user at this point.
