### ISSUE TITLE
Dockerize browser

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#682]
Sandbox Chrome and provide a secure way to communicate with it over WebSocket. Another idea is to dockerize both the xk6-browser extension and browser into a single container.

Suggestion:
Use a docker container to launch a Chromium instance, parse the DevToolsURL, and map the port to a fixed port on the container so that xk6-browser can connect to the same port.

More details TBA.

**Comment by inancgumus** [comment]
Removing this from this milestone as we need to make more tests and also plan the cloud part of the merge in the next milestone.

**Comment by ankur22** [comment]
Deprioritised for now since we're approaching this with a different solution.

**Comment by ankur22** [comment]
Could we also add a way to blacklist certain urls/hostnames (related: #787) instead of relying on xk6-browser or the browser itself to block them?

**Comment by inancgumus** [comment]
Hey, @ankur22, I think we can close this one and track it from the other issue (you know which).
