### ISSUE TITLE
Merge xk6-browser into k6

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#710]
We need to make the change in the `k6` repo to allow browser to be experimental.

Related: https://github.com/grafana/k6/pull/2884

Here is the example from a previous such merge in `k6`:
- https://github.com/grafana/k6/commit/da648a9c927a1a0ca4cac7640dadc6ec9af17df8

**Comment by inancgumus** [comment]
I'm adding this issue to https://github.com/grafana/k6-cloud/issues/752.
