### ISSUE TITLE
Reduce dependency usage

### ISSUE THREAD

**Issue by ka3de** [grafana/xk6-browser#729]
Some dependencies currently required by the project are marginally used and could potentially be removed. This acquires more relevance with the upcoming merge with k6 core due to the importance that is placed in this project to minimize the dependencies usage and limit its heterogeneity in order to prevent malfunctions between extensions code.

Some examples for dependencies that could potentially be reevaluated are:
- [github.com/hashicorp/go-multierror](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/common/remote_object.go#L16)
- [github.com/fatih/color](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/log/logger.go)
- ~~[github.com/mccutchen/go-httpbin/httpbin](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/tests/ws/server.go#L22): Although in this case this one has 0 transitive dependencies~~ -> Not included in binary as is only required in `tests` package.
- [github.com/oxtoacart/bpool](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/k6ext/k6test/vu.go#L15): Only 1 transitive dependency for testify, which is nevertheless used in xk6-browser anyway.

Other dependencies such as:
- golang.org/x/exp
- golang.org/x/net
- ~~golang.org/x/sync~~ -> Only used in `tests` pkg
- gopkg.in/guregu/null.v3
Are marginally used but are required as transitive dependencies by other modules.

Additionally this is in interest of reducing the xk6-browser / k6 binary size.

**Comment by ka3de** [comment]
In regards of github.com/fatih/color usage:

A couple of points of view.
From one side, color library is only used in the logger implementation, and only when the "inner logger" is nil. See [here](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/log/logger.go#L91-L95).
But in practice this never happens, as in our implementation, every time that a logger is created, we pass the `vu.State().Logger` as the inner logger. See references [1](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/common/response.go#L74), [2](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/common/network_manager_test.go#L66)(also it's a test), [3](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/common/network_manager.go#L77), [4](https://github.com/grafana/xk6-browser/blob/5bd4fa1d7d9c9345eeee8107a97c021b7fee08b2/chromium/browser_type.go#L401).
So we could probably replace this by a simpler implementation from our side.

On the other hand this library is already being [used](https://github.com/grafana/k6/blob/1d99b0be9194bf9aaf86c070dd0d34604f266abe/go.mod#L12) by k6 core, so probably there's no need to remove it as it'll be included in the final binary anyway?

**Comment by ankur22** [comment]
Re. github.com/fatih/color

> color library is only used in the logger implementation, and only when the "inner logger" is nil

Based on how k6 works with dependencies, we should remove it, which would be my preference too.
