### ISSUE TITLE
Got error when tried to run example

### ISSUE THREAD

**Issue by mfrow** [grafana/xk6-browser#731]
### Brief summary

![2023-01-26_11h13_55](https://user-images.githubusercontent.com/19708825/214849694-f8ddfe71-2c71-4e84-9e06-d3d6930a3d27.png)

the same error occurs for other examples

### xk6-browser version

7.0

### OS

Windows 10

### Chrome version

 109.0.5414.75

### Steps to reproduce the problem

I got an error when tried to run the example:

1. Clone the xk6-browser repo
2. Run: go install go.k6.io/xk6/cmd/xk6@latest
3. Run: xk6 build --output xk6-browser.exe --with github.com/grafana/xk6-browser
4. Run the example: .\xk6-browser run examples\fillform.js
I got the following:
![2023-01-26_11h13_55](https://user-images.githubusercontent.com/19708825/214849694-f8ddfe71-2c71-4e84-9e06-d3d6930a3d27.png)

the same error occurs for other examples

### Expected behaviour

examples should pass

### Actual behaviour

All the examples failed

**Comment by ankur22** [comment]
Hi @mfrow,

I've left a comment in the original [discussion](https://github.com/grafana/xk6-browser/discussions/730), let me know if that helps.

Cheers,
Ankur

**Comment by mfrow** [comment]
I tested the steps 
https://github.com/grafana/xk6-browser/discussions/730 
and it works
