### ISSUE TITLE
Daily CI run should trigger an alert on failure

### ISSUE THREAD

**Issue by ka3de** [grafana/xk6-browser#732]
After setting up daily CI `e2e` and `test` runs in #701 we have reduced the feedback loop on possible compatibility issues with k6 core modifications. Now we should put a mechanism in place (besides the workflow "dashboard" in GH) in order to be alerted on a centralized point for the team in case one daily CI execution fails.

**Comment by ka3de** [comment]
Done.

**Comment by inancgumus** [comment]
Removing the blocking-note. @ka3de
