### ISSUE TITLE
Not Able to Select Code in grafana UI using xk6 browser tool. 

### ISSUE THREAD

**Issue by jaswanth99999** [grafana/xk6-browser#733]
I am trying to use xk6-browser load testing tool on grafana UI. And i want to do a query using the Tool. In the grafana UI when i am trying to shift from Builder to Code which is of Type radio I am getting error as `getting element position: node is either not visible or not an HTMLElement`. U can see in the below image .

![image](https://user-images.githubusercontent.com/79706758/215038069-abedb65b-f274-4474-bb2b-d4a184762c7a.png)

The code i am using is 

```
    let code_button=page.$("input[checked]");
    code_button.click();
    page.waitForSelector('div[data-testid="loki-editor"]',{ timeout: 50000 })
    sleep(5)
    page.screenshot({ path: '/Users/jaswanthcherukuri/xk6-browser/test/screenshot6.png' });
    console.log("Exit");
    sleep(10);
```

The error I am getting is 

`ERRO[0049] Uncaught (in promise) clicking on element: getting element position: node is either not visible or not an HTMLElement  executor=per-vu-iterations scenario=default`

There are no distinct elements in the html code for the both builder and code. Any help is appreciated.

**Comment by ka3de** [comment]
Hi @jaswanth99999 ,
Could you please open a ticket for this in our [community forum](https://community.k6.io/c/xk6-browser)? We will handle the issue from there.
Thank you.
