### ISSUE TITLE
Map Page's Keyboard, Mouse, and Touchscreen properties

### ISSUE THREAD

**Issue by ka3de** [grafana/xk6-browser#749]
### Brief summary

In v0.8.0, probably due to the change on how the mapping is done from xk6-browser components to Goja, the `keyboard` and `mouse` elements are no longer exposed in the JS API.

I think this also proves that we need more tests / examples for these functionalities from the JS API side.

### xk6-browser version

v0.8.0

### OS

Ubuntu 20.04.5 LTS

### Chrome version

109.0.5414.119 (Official Build) (64-bit)

### Steps to reproduce the problem

Run this script which actually works with v0.7.0 version, but not for v0.8.0:

```js
export default function () {
    const browser = chromium.launch({ headless: false, timeout: "10m" });
    const page = browser.newPage();
  
    page.goto("https:/duckduckgo.com/", { waitUntil: 'networkidle' })
    .then(() => {
        console.log(page.keyboard); // prints undefined
        console.log(page.mouse); // prints undefined
        
        page.keyboard.type('k6');
        page.keyboard.press('Enter');
        sleep(3);
    })
    .finally(() => {
        page.close()
        browser.close()
    });
}
```

### Expected behaviour

Error execution printing undefined for both `keyboard` and `mouse` elements of `page` and fails due to keyboard being undefined.
<details>
<summary>See error log.</summary>

```shell
INFO[0001] undefined                                     source=console
INFO[0001] undefined                                     source=console
ERRO[0001] Uncaught (in promise) TypeError: Cannot read property 'type' of undefined or null
running at file:///<redacted>/test.js:30:13(15)  executor=per-vu-iterations scenario=default
```
</details>

### Actual behaviour

The script should type in `k6` in the search bar, submit by pressing `Enter` through the `page.keyboard` element and finish its execution correctly.

**Comment by inancgumus** [comment]
Agreed. See: #675
