### ISSUE TITLE
Create documentation for the Mouse class

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#766]
### Description

The current documentation is linking to PW docs. We should bring these doc to align with the existing classes that we've documented e.g. [Browser](https://k6.io/docs/javascript-api/xk6-browser/api/browser/).

### Suggested Solution (optional)

Add the docs for `Mouse` class in the [k6-docs repo](https://github.com/grafana/k6-docs/tree/main/src/data/markdown/docs/02%20javascript%20api/07%20k6-experimental/01%20browser)

**Comment by inancgumus** [comment]
Closed by https://github.com/grafana/k6-docs/pull/1594
