### ISSUE TITLE
Browser is getting crashed when navigating to the application due to panic error "unexpected end of JSON input"

### ISSUE THREAD

**Issue by ostandsouza** [grafana/xk6-browser#777]
### Brief summary

The browser(Chrome) crashes on navigation to the application. Below is the error
**panic: GoError: parsing remote object value: unexpected end of JSON input**

This is reproducible only in one application of ours, on other application it is working fine. My guess is probably one of api response is too long for it to parse.

Attached K6 logs with debug flag enabled.
[log.txt](https://github.com/grafana/xk6-browser/files/10708987/log.txt)

### xk6-browser version

v0.80.0

### OS

macOS 12.6

### Chrome version

109.0.5414.119

### Steps to reproduce the problem
```javascript
import { chromium } from 'k6/x/browser';
import {sleep} from 'k6';

// export const options = { vus: 1, duration: '2m' }

export default function () {
    const browser = chromium.launch({ 
        args: [],
        headless: false, 
        debug: true,
        args: ['--start-maximized'],
        timeout: "60s",
        slowMo: "1000ms",
        proxy: {},
        env: {},
        executablePath: null,
        devtools: true
    });
    const context = browser.newContext({
        acceptDownloads: true,
        ignoreHTTPSErrors: true,
        JavaScriptEnabled: true,             // Whether to accept downloading of files by default
    });
    context.setDefaultNavigationTimeout(60)
    context.setDefaultTimeout(60)
    
    const page = context.newPage();

    page.goto(*applicationURL*, { waitUntil: 'networkidle' });

    page.waitForLoadState();
    page.waitForSelector("button.mat-focus-indicator>span")
    page.screenshot({path:'screenshots/01_LoginPage.png'})
   
}
```
### Expected behaviour

Should be able to navigate and proceed with the rest of the execution.

### Actual behaviour

Crashing on navigation itself

**Comment by angelo-loria** [comment]
Here's a reproducible example with xk6-browser 0.80

```
import { chromium } from 'k6/x/browser';

export default function () {
  const browser = chromium.launch({ headless: false });
  const page = browser.newPage();

  page
    .goto('https://apply.mykaleidoscope.com/')
    .then(() => {
        page.screenshot({ path: 'screenshot.png' });
    })
    .finally(() => {
      page.close();
      browser.close();
    });
}
```

**Comment by ostandsouza** [comment]
Do we have any update on this? We're blocked for more than 2 weeks now. Kindly let us know if there are any alternatives available. Your suggestion is most welcome.

**Comment by ka3de** [comment]
Hi @ostandsouza,
Thank you for submitting this issue and apologies for late reply. Indeed looks like a bug, but we have to investigate this better. We'll get back to you once we have diagnosed the exact behavior and root cause.

**Comment by ka3de** [comment]
Hi @ostandsouza , we have diagnosed the issue. The website is printing some `null` messages in the console log and this are mishandled by xk6-browser implementation, resulting in the error that is shown in your cmdline output.

We have created an issue with more specific details. You can track it's progress here https://github.com/grafana/xk6-browser/issues/793.
