### ISSUE TITLE
Cloud Research

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#789]
I've noticed that we often create Github issues for small research tasks that can be completed in a few hours. While this can help track progress and stay organized, it can also create many issues and make it harder to focus on **the big picture**.

To address this, I propose the following:
* Batching research tasks related to the Cloud in this issue
* Noting the research results in this issue or a Google Docs document and linking it here.

This will help us to keep the number of issues manageable and reduce the overhead of managing multiple issues. If you agree with this approach, please let me know. Please feel free to add your own small tasks to this issue or suggest other ideas for how we can work more effectively together.

---

# Research

## Work with the existing blacklist (#787)

We have a blacklist, and we need to ensure that xk6-browser some how works with that. This is both an investigative issue and one that requires the solution if we can implement it. We may need another way if we can't control the browser's blacklist (if there is such a thing) from k6-browser and please combine it with or implement after https://github.com/grafana/xk6-browser/issues/682.

### Result

As far as i can tell there's no way to configure chrome to accept a list of blocked urls/hostnames. This will need to be done with docker.

## Can we auth/secure the websocket connection with the browser? (#786)

N/A

### Result

Not possible out of the box. We would need to proxy the websocket connection.

## Can the browser store screenshots in a given path? (#785)

We need to investigate whether it's possible to store screenshots into a given directory.

### Result

The browser streams the screenshot data back to xk6-browser over the websocker, and xk6-browser writes it to disk. So browser definitely no. xk6-browser works locally, but it can't in any other way at the moment.

## Next research

Please add only the title, not another micro issue 😅 

@grafana/k6-browser @andrewslotin

**Comment by ka3de** [comment]
Hey @inancgumus thanks for thinking on improving our organization, I definitely find it a little bit chaotic sometimes.

In regards of this specific proposal, I thought we already had a "grouping" task for the whole cloud implementation that we could use to track the global status with #752 . Doesn't that work to reflect the big picture?

If I understood correctly, the intention of this is to group only the research tasks? And group them as text (headers) in a single issue description? I can see that, in the current case it's true that we had a couple of small issues, but at the same time I see a considerable con of having all the "tasks" defined in a single issue, which is that discussions in the issue will be mixed for the different topics and might make it more difficult to come to a conclusion. Instead in separate issues the focus on each topic is clear.

Let me know if I misunderstood something.
I'm open to discuss it with the team and try to improve on this!

**Comment by inancgumus** [comment]
I agree. Having tasks in the issue description is not optimal.

Instead, I would propose:

- Creating a Google Docs document.
- And putting all the research tasks in it.

Then we can put a link to that document in [the overarching tracking issue #752](https://github.com/grafana/k6-cloud/issues/752). This can allow us to easily see the big picture without overcrowding our issue tracker.

WDYT?

**Comment by inancgumus** [comment]
Thanks, @ka3de.

I agree. Having tasks in the issue description is not optimal.

Instead, I would propose:

- Creating a Google Docs document.
- And putting all the research tasks in it.

Then we can put a link to that document in [the overarching tracking issue #752](https://github.com/grafana/k6-cloud/issues/752). This can allow us to easily see the big picture without overcrowding our issue tracker.

WDYT?

**Comment by ka3de** [comment]
I think that would be better, yes! :+1: 
I think that can be a good option, although would like to hear the rest of the team's opinions on this, as I'm always a little doubtful as to how to organize/separate the cloud vs the OSS issues/tasks. But this seems like a good approach to balance that, even if we'll have a link to a private document in a GH issue.
