### ISSUE TITLE
Upload screenshot data when remote storing service URL is set by the environment

### ISSUE THREAD

**Issue by ka3de** [grafana/xk6-browser#839]
Under some circumstances, when a remote storing service URL is set by the environment, xk6-browser should not store screenshots locally, but instead upload its data to the storing service.

A consideration to take into account in order to implement this is to possibly fulfill this pending [TODO](https://github.com/grafana/xk6-browser/blob/c9ae92ae50c2a3cba5202464f9fe52e641be2be2/common/screenshotter.go#L179) comment and refactor screenshot storing in order to be async.

Also, we should evaluate how running k6/k6 browser with `--out cloud` should behave for screenshots data.

Related: #808

**Comment by ka3de** [comment]
Superseeded by https://github.com/grafana/k6/issues/3017

**Comment by ka3de** [comment]
Closing as not planned.

**Comment by ka3de** [comment]
Closing as not planned.

**Comment by ka3de** [comment]
Reopening as the current approach is to implement this first directly from k6 browser instead of relying on https://github.com/grafana/k6/issues/3017.

**Comment by ankur22** [comment]
I believe the upload of the screenshots has been done to a satisfactory degree. We may need to iterate on it, but we will open new issues for new changes.
