### ISSUE TITLE
Installation failing with `parsing go.mod:`

### ISSUE THREAD

**Issue by QAInsights** [grafana/xk6-browser#84]
I am trying to install `xk6-browser`. But I am getting the below error in Windows 10. 

Go version: `1.17.3`.

![image](https://user-images.githubusercontent.com/2826376/141049621-ece61032-7769-486f-9032-c03f919d0da9.png)

**Comment by inancgumus** [comment]
Hi, thanks for letting us know.

Can you try the following:

`go install go.k6.io/xk6/cmd/xk6@latest`

**Comment by Alexbirvik** [comment]
@inancgumus Maybe it's a good idea to replace the command in the article:
https://k6.io/blog/announcing-xk6-browser-testing/
