### ISSUE TITLE
Generate TypeScript Type declarations for Page API

### ISSUE THREAD

**Issue by ka3de** [grafana/xk6-browser#840]
Individual task to generate type declarations for the `Page` API.
See current k6 type declarations in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/k6) repository.

Related: https://github.com/grafana/xk6-browser/issues/791

**Comment by ankur22** [comment]
PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65248 merged.
