### ISSUE TITLE
Tag web vitals metrics to have more fine grained querying

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#862]
When web vital metrics are emitted, xk6-browser is currently [tagging them with the URL](https://github.com/grafana/xk6-browser/blob/6cf07385e1673dcb814568a273dcbd31e898e4a5/common/frame_session.go#L317-L321). This allows anyone to query the emitted metrics and find the web vital metrics for specific urls. In most cases this is probably good enough.

We would like to extend the implementation of how web vital metrics are emitted to allow us to do two things:
1. query them so that we can display them in a timeline.
2. query them so that we can group "related" navigations.

## Query them so that we can display them in a timeline

Let's say I have a test which is doing the following steps:

1. `goto` (https://test.k6.io/my_messages.php)
1. `fill` username and password
1. `click` login
1. Page navigates to the same url but this time the messages load (https://test.k6.io/my_messages.php)

This test visits the same url twice, but the state changes between the two navigations, which means that the web vital metrics will differ between the two. At the moment there isn't a simple way to group the two sets of web vital metrics which were emitted when visiting the same url.

The task here is to find a way to group the web vital metrics so that anyone can query the metrics based on an attribute that denotes an order in time. E.g.:

| url | metric | value | order |
| - | - | - | - |
| https://test.k6.io/my_messages.php | web_vital_cls | 0.45 | 0 |
| https://test.k6.io/my_messages.php | web_vital_lcp | 200 | 0 |
| https://test.k6.io/my_messages.php | web_vital_fid | 300 | 0 |
| https://test.k6.io/my_messages.php | web_vital_cls | 0.45 | 1 |
| https://test.k6.io/my_messages.php | web_vital_lcp | 600 | 1 |
| https://test.k6.io/my_messages.php | web_vital_fid | 400 | 1 |

## Query them so that we can group "related" navigations

Now let's work with the following example:

1. `Goto` to navigate to [test.k6.io](http://test.k6.io/);
1. `Click` to navigate to /my_messages.php;
1. `Goto` to navigate to [test.k6.io](http://test.k6.io/);
1. `Click` to navigate to /news.php;
1. etc.

After being able to query the web vital metrics so that we can pull them based on an attribute that denotes an order in time, we would next like to group them based on "related" navigations. What I mean by that is we would like to display the top level `goto` actions and under them the other navigations that have occurred due to other actions (such as `click`ing on a button or link).

## Tasks

```[tasklist]
### Tasks
- [ ] Find a way to group the web vital metrics so that anyone can query the metrics based on an attribute that denotes an order in time
- [ ] Find a way to group "related" navigations, where `goto` is a top level action and other actions which cause navigations are a level below.
```

**Comment by inancgumus** [comment]
We now have a better idea of the problem. We can close it and recreate a new issue if needed after the investigation.
