### ISSUE TITLE
fails if any loaded sub-resource fails

### ISSUE THREAD

**Issue by tmc** [grafana/xk6-browser#882]
### Brief summary

For example, if an XHR request is sent over to sentry and sentry 429's the request, it appears the whole page.goto() call fails and I don't see a way to control the behavior (missing playwright-like `route()` api?).

### xk6-browser version

k6: v0.44.1

### OS

macos

### Chrome version

113.0.5672.92

### Steps to reproduce the problem

page.goto() to a page that has an XHR call that 429s

### Expected behaviour

Some means of not considering a sub-resource failure an overall failure.

### Actual behaviour

a 429 on an XHR calls seems to fail the whole page.goto()

**Comment by ankur22** [comment]
Thank you for submitting this bug report @tmc! Could you please add a sample test script that points to a publicly accessible site so that we can test and work against it? It would also help if you could copy and paste the error message in the description too.

**Comment by tmc** [comment]
I think I was misunderstanding the output. I can't get further here as cloudflare isn't allowing me to proceed as it's detecting a non-human actor (understandably).
