### ISSUE TITLE
Parse instance scenarios into a flat WS URL list

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#888]
The k6-browser can connect to browsers in a round-robin fashion by retrieving data from the `K6_INSTANCE_SCENARIOS` environment variable.

## Problem

Currently, we [consider](https://github.com/grafana/xk6-browser/blob/dc0a4789f06778d03b5c2e5aad17814e1555bcca/k6ext/env.go#L18) a list of WS URLs.

However, instead of receiving a flat list of WS URLs, we will receive the following minified JSON via the `K6_INSTANCE_SCENARIOS` environment variable:

```bash
K6_INSTANCE_SCENARIOS="[{\"id\":\"one\",\"browsers\":[{\"handle\":\"ws://1...\"},{\"handle\":\"ws://2...\"}]},{\"id\":\"two\",\"browsers\":[{\"handle\":\"ws://3...\"}]}]"
```

The pre-minified JSON looks like the following (where `id` is a scenario ID/name):

```json
[
    {
        "id": "one",
        "browsers": [
            { "handle": "ws://1..." },
            { "handle": "ws://2..." }
        ]
    },
    {
        "id": "two",
        "browsers": [
            { "handle": "ws://3..." }
        ]
    }
]
```

## Solution

Currently, we don't support other browsers than Chromium. And we don't need to respect the scenario details to pool WS URLs in each scenario. So we can parse the source JSON into the following, a flat list of WS URLs by joining all scenarios into one as follows:

```json
[ "ws://1...", "ws://2...", "ws://3..." ]
```

With this, we can still use the same feature set in the k6-browser without changing anything else. And we can be ready when we support other browsers (since we'll be getting WS URLs in scenarios based on environmental details like browser types).

## Suggestion

Change the `IsRemoteBrowser` function to parse the scenario-based JSON data into a flat list of WS URLs.

**Comment by ankur22** [comment]
Now we are reading the WS URL in the `mapBrowserToGoja` function. The scope is per `VU` lifecycle? So we're parsing the map once every `vu` when it's probably ok to parse once and use when we need.

A possible solution to this could be:
1. Parse the ENV variable once. So maybe when we create the `RootModule`?
2. Keep the list of WS URLS in the `RootModule`
3. Pass a reference to the list to the `VUmodule` when called to `NewInstanceModule` (same way we do for `pidRegistry`)
4. And then for each iteration we can call something like.... `vu.IsRemoteBrowser()` Which would return `true`/`false` if it's remote, and if it is remote then it will return one WS URL randomly from the initially parsed list.

**Comment by inancgumus** [comment]
Hey, @ankur22! Thanks for tackling with this 🙇

Our primary goal here is to make sure everything works smoothly with the BE data. To do this, we can easily transform the instance scenario JSON data into a more straightforward list of WS URLs. Simple as that!

I really like the solution you proposed! 😊 However, I think it might be a good idea to tackle them separately, perhaps in a different issue or pull request (PR).
