### ISSUE TITLE
`Request.frame` is sometimes nil

### ISSUE THREAD

**Issue by imiric** [grafana/xk6-browser#90]
Sometimes when we create a new `Request` here:
https://github.com/grafana/xk6-browser/blob/9882ab5e0390cd12cea19165a6786c4b9c463774/common/network_manager.go#L342-L350

... we get a nil `Frame` pointer from `FrameManager.getFrameByID()`.

The logic of how `m.frames` is changed is a bit convoluted, as we delete frames in a couple of places:
- https://github.com/grafana/xk6-browser/blob/9882ab5e0390cd12cea19165a6786c4b9c463774/common/frame_manager.go#L185
- https://github.com/grafana/xk6-browser/blob/9882ab5e0390cd12cea19165a6786c4b9c463774/common/frame_manager.go#L295

We added some debugging information in 0451efb so we can see when it happens, but there's likely a synchronization bug here that we need to address so that anything that needs a `Frame` reference (e.g. when getting the session through it for [`Response.fetchBody()`](https://github.com/grafana/xk6-browser/blob/9882ab5e0390cd12cea19165a6786c4b9c463774/common/response.go#L140) (which we could possibly store directly on `Response` to avoid resolving the reference chain?)) can run before we actually delete the `Frame`.

**Comment by imiric** [comment]
Some more info about this: from testing with the script in #49, when we get a nil `Frame` in [`NetworkManager.onRequest()`](https://github.com/grafana/xk6-browser/blob/9882ab5e0390cd12cea19165a6786c4b9c463774/common/network_manager.go#L342-L350) it's because `event.FrameID == ""`, i.e. there's no `Frame` associated to the `RequestWillBeSent` event to lookup. In all cases these are preflight/`OPTIONS` requests, which typically don't have a body anyway, though [this is not strictly forbidden by the spec](https://stackoverflow.com/questions/11926908/how-to-respond-to-an-http-options-request#comment66715405_11930225). So if the responses have `Content-Length` we would emit metrics for them fine and won't rely on `Response.fetchBody()`/CDP.

That said, the reason `fetchBody()` fails so often is because calling `network.GetResponseBody()` shouldn't be done on the `ResponseReceived` event, but on the `LoadingFinished` one. See https://github.com/ChromeDevTools/devtools-protocol/issues/44#issuecomment-320127404.

So the fix I'm currently working on involves emitting metrics for Response only in the `LoadingFinished` handler, which does produce less `error fetching response body` warnings, but I'm running into an issue where _sometimes_ we don't get a `ResponseReceived` event before we get `LoadingFinished`, so [the Response we set on the Request](https://github.com/grafana/xk6-browser/blob/9882ab5e0390cd12cea19165a6786c4b9c463774/common/network_manager.go#L401) is nil. Not sure why this happens, the flow should be `RequestWillBeSent -> ResponseReceived -> LoadingFinished`.

An alternative to using `network.GetResponseBody()` and `len(r.body)` to emit `data_received` metrics could be to use [`EventLoadingFinished.EncodedDataLength`](https://github.com/chromedp/cdproto/blob/d3760c2dc57baf9f88aeef1f1fbb2fd9c8a4cc12/network/events.go#L50). This seems like it would be more reliable, yet I've seen cases where this is `0.0` and `len(r.body) > 0`. So... :man_shrugging: I'll have to look deeper into this.

**Comment by inancgumus** [comment]
This is in the review queue. You didn't request me to review this yet but should I add my review to this? @imiric

**Comment by imiric** [comment]
The PR for this is #117. It's still a draft because of the race condition it introduces, which I'm not sure how to fix yet, and well, other issues have come up in the meantime.

**Comment by imiric** [comment]
I think we can close this. As explained [above](https://github.com/grafana/xk6-browser/issues/90#issuecomment-966477394), `Frame` being nil is a valid state, and we no longer panic because of it. After #117 it's being logged with more detail, and `fetchBody()` is more reliable, so we shouldn't see it as often.

WDYT @inancgumus?

**Comment by inancgumus** [comment]
Let's merge 🚀
