### ISSUE TITLE
Configuration web browser

### ISSUE THREAD

**Issue by cosmind-rusu** [grafana/xk6-browser#924]
### Feature Description

Hi, I’m doing tests with k6 browser and I need to access a website, but to be able to enter that website I first have to go to the browser settings, go to the unsafe content tab and put the url of the site I want to access with the test there. The problem is that I can’t find any way to do it. I would need to go to the browser settings while running the test and put the site there at that time. I would appreciate it if someone could help me if they have had this need at some point and if not, it could be a new possible function to add a pre-test configuration file like the one playwright can have. Best regards.

**Comment by ka3de** [comment]
Hi @cosmind-rusu ,
Could you create a ticket for this in our [community forum](https://community.k6.io/c/k6-browser/14) so we can address it from there please?
Thank you.
