### ISSUE TITLE
Implement `Browser.on(event)`

### ISSUE THREAD

**Issue by robingustafsson** [grafana/xk6-browser#95]
Add support for `Browser.on(event)`, to allow listening and reacting to browser events.

**Relevant links**:
- Playwright docs: https://playwright.dev/docs/api/class-browser#browser-event-disconnected

**Comment by imiric** [comment]
We should leave this open until proper integration tests can be added, once https://github.com/grafana/k6/pull/2399 is merged. #268 only added a happy path E2E test, but we should also test the Promise rejection by cancelling the context.
