### ISSUE TITLE
Frame requestByID panics when initializing networking

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#986]
### Brief summary

There is a flaky bug in `(*Frame).requestByID` that happens while initializing `(*NetworkManager).initEvents`. The test run ID is 155045.

### xk6-browser version

0fcdd36

### OS

Linux

### Steps to reproduce the problem

Run the following script on a resource restricted platform _several times_ as the issue is flaky.

<details>
<summary>The script</summary>

```js
import { browser } from 'k6/experimental/browser'
import { check } from 'k6'

export const options = {
  scenarios: {
    browser: {
      executor: 'per-vu-iterations',
      maxDuration: '15m',
      vus: 5,
      iterations: 10,
      options: {
        browser: {
          type: 'chromium',
        },
      },
    },
  }
}
export default async function () {
  const page = browser.newPage();

  try {
    // User journy in SPA application
    await page.goto('https://.../'); // TODO: change it to the otel app

    const productCard = page.locator('(//div[@data-cy="product-card"])[1]')
    productCard.click()

    const quantityOption = page.locator('[data-cy="product-quantity"]')
    quantityOption.selectOption('3')
    const addToCardBtn = page.locator('[data-cy="product-add-to-cart"]')
    addToCardBtn.click()

    check(page, {
      'cart item name': page => page.locator('//p[text()="National Park Foundation Explorascope"]').isVisible() === true,
      'cart item quantity': page => page.locator('//p[text()="3"]').isVisible() === true
    })

    // Check GH link to force another navigation
    await Promise.all([
      page.waitForNavigation(),
      page.locator('footer a').click(),
    ]);
    check(page, {
      'gh-author': page.locator(
        'div#repository-container-header span.author a'
      ).textContent().includes('open-telemetry'),
    });
  } finally {
    page.close();
  }
}
```

</details>

### Expected behaviour

No panics.

### Actual behaviour

```go
goroutine 246996 [running]:
github.com/grafana/xk6-browser/common.(*Frame).requestByID(0xc0089428c0, {0xc009718454, 0x7})
	github.com/grafana/xk6-browser@v1.0.0-rc0.0.20230726091449-0fcdd3618f29/common/frame.go:365 +0x5a
github.com/grafana/xk6-browser/common.(*FrameManager).requestFailed(0xc001d700c0, 0xc0055d4640, 0x0)
	github.com/grafana/xk6-browser@v1.0.0-rc0.0.20230726091449-0fcdd3618f29/common/frame_manager.go:450 +0x4d7
github.com/grafana/xk6-browser/common.(*NetworkManager).onLoadingFailed(0xc008dd3ea0, 0xc007489200)
	github.com/grafana/xk6-browser@v1.0.0-rc0.0.20230726091449-0fcdd3618f29/common/network_manager.go:345 +0x116
github.com/grafana/xk6-browser/common.(*NetworkManager).handleEvents(0xc008dd3ea0, 0xc004206960)
	github.com/grafana/xk6-browser@v1.0.0-rc0.0.20230726091449-0fcdd3618f29/common/network_manager.go:318 +0x288
github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents.func1()
	github.com/grafana/xk6-browser@v1.0.0-rc0.0.20230726091449-0fcdd3618f29/common/network_manager.go:301 +0x37
created by github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents
	github.com/grafana/xk6-browser@v1.0.0-rc0.0.20230726091449-0fcdd3618f29/common/network_manager.go:300 +0x14d
```
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/xk6-browser/pull/1220
- [ ] https://github.com/grafana/xk6-browser/pull/1246
- [ ] https://github.com/grafana/k6/pull/3652
```

**Comment by inancgumus** [comment]
Shouldn't `click` be called with `await`? 🤔

**Comment by ankur22** [comment]
While taking a look at this discussion [here](https://github.com/grafana/xk6-browser/discussions/1218), I looked through the code again and it does indeed seem that the issue lies on line [412](https://github.com/grafana/xk6-browser/blob/5f754c2c2252896016fd77d1fd3234a795049a0e/common/frame.go#L412) which would indicate that the original `frameSession` from line [408](https://github.com/grafana/xk6-browser/blob/5f754c2c2252896016fd77d1fd3234a795049a0e/common/frame.go#L408) was `nil`, and either the `mainFrameSession` or the `networkManager` in the `mainFrameSession` were `nil`.

I think the best course of action is:
1. Protect against NPD by ensuring that both the `mainFrameSession` and its `networkManager` are not `nil`, and log a warning.
2. Replicate the issue to diagnose exactly why we get into this state.

**Comment by inancgumus** [comment]
I agree that we need to first determine which one (or both) is nil. We can add a simple logger to determine 👍

**Comment by ankur22** [comment]
As a step towards understanding the root cause we've created https://github.com/grafana/xk6-browser/pull/1220 to help us identify exactly which component is `nil`. We might be in a better position to find the root cause of the issue once we see the logs.

**Comment by inancgumus** [comment]
Closed by #1219.

**Comment by ankur22** [comment]
We've seen more cases of this even after https://github.com/grafana/xk6-browser/pull/1219. Reopening.

**Comment by joanlopez** [comment]
> Happened in test run ID: 2480444 (prod).

Another occurrence in test run ID: 2539482 (prod).
