### ISSUE TITLE
Upload a file with k6 Browser and interact with explorer

### ISSUE THREAD

**Issue by charbel-hanna-shift** [grafana/xk6-browser#995]
### Feature Description

in some of the scenarios we need to test the performance of uploading files from the UI.
for that we need k6 browser to be able to interact with explorer since in most scenarios, when you click on "Upload Button" a windows explorer tab will open where you can select the file to be uploaded.

**Comment by mdcruz** [comment]
Supporting [FileBrowser API](https://playwright.dev/docs/api/class-filechooser) will allow us to do this.

**Comment by inancgumus** [comment]
Thanks @charbel-hanna-shift. I'm closing this one as it is a duplicate. Could you give a thumbs-up to the original issue #99 or add a comment if you like?

Duplicate: #99.
